### ISSUE TITLE
complete pipeline validations

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1002]
We need to do an exhaustive validation on incompatible/unsupported pipeline states

Validate the following:
- [x] forests
- [x] dangling vertices
- [x] #974 
- [x] disallow if sink is not the last vertex

**Comment by juliev0** [comment]
I could potentially do this along with [this](https://github.com/numaproj/numaflow/issues/974) one that's related. Or if anyone else works on it, just make sure that if you're traversing vertices that you don't get into an infinite loop now that we can have cycles. Note [this](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/pipeline/validate.go#L413) method may or may not be useful.

**Comment by vigith** [comment]
I have added #974 to the list

**Comment by juliev0** [comment]
One way to look at the forest problem: If you start with any Vertex and from there you traverse "from" and "to" and you stop whenever you hit something that you already visited, you can compile a unique Set. Then you can verify that the length of that Set is equal to the number of Vertices. If it's less than the number of Vertices then you have a forest.
