### ISSUE TITLE
Numaflow server v1_1 APIs

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1031]
# Summary

As we are building new Numaflow UX, we need a new set of RESTful APIs (v1_1) for new UX components.

- [ ] Scaffold the code structure for v1_1 routing.
- [ ] xxx
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jy4096** [comment]
TODOs
1. server/apis/v1/handler.go
(159, 8) // TODO(API) : Get the current status of the ISB service
(274, 5) // TODO: the client should be cached.
(395, 5) // TODO: validate the patched data as well, e.g. only allow lifecycle to be patched
(458, 5) // TODO(API) : Get the current status of the ISB service
(508, 5) // TODO: validate if it's being used by any pipelines
(523, 5) // TODO: the client should be cached.
(544, 5) // TODO: the client should be cached.
(624, 5) // TODO: the client should be cached.
(825, 6) // TODO(API) : Get the current status of the ISB service
(833, 4) // TODO(API): Change the Daemon service to return the consolidated status of the pipeline

2. server/apis/v1/routes/routes.go
(30, 5) // TODO: Get the version of the current Numaflow

3. e2e missing tests (at least 1 test)
r.PUT("/namespaces/:namespace/pipelines/:pipeline", handler.UpdatePipeline)
r.PATCH("/namespaces/:namespace/pipelines/:pipeline", handler.PatchPipeline)
r.PUT("/namespaces/:namespace/isb-services/:isb-services", handler.UpdateInterStepBufferService)
r.PUT("/namespaces/:namespace/pipelines/:pipeline/vertices/:vertex", handler.UpdateVertex)
r.GET("/metrics/namespaces/:namespace/pods/", handler.ListPodsMetrics) // tested in postman but got 301 error code in e2e test
r.GET("/namespaces/:namespace/pods/:pod/logs", handler.PodLogs) // tested in postman but failed to add in e2e test
r.GET("/namespaces/:namespace/events", handler.GetNamespaceEvents)
r.POST("/validation/pipeline", handler.ValidatePipeline)
r.POST("/validation/isb-service", handler.ValidateInterStepBufferService)

4. e2e api-test improvement
