### ISSUE TITLE
improve JOIN vertex doc

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1071]
Add more documentation to [JOIN vertex](https://numaflow.numaproj.io/user-guide/reference/join-vertex/) from the [blog](https://blog.numaproj.io/from-trees-to-directed-graphs-4e59f0463cfc).

**Comment by VishalSoni07** [comment]
Hi, @vigith,

I would like to work on this as part of Hacktoberfest 2023. Can you please assign this to me?

**Comment by VishalSoni07** [comment]
Hi @whynowy, @vigith,
Can you please review this PR: https://github.com/numaproj/numaflow/pull/1173 to fix this issue?
