### ISSUE TITLE
hacktoberfest in github topic

### ISSUE THREAD

**Issue by tczhao** [numaproj/numaflow#1073]
# Summary

Hi @vigith 
I saw you created a few issues with hacktoberfest label
However, according to [hacktoberfest ](https://hacktoberfest.com/participation/), you need to have "hacktoberfest" topic in the github repo to make this repo available to hacktoberfest.

Could you please add hacktoberfest topic to the repo
![image](https://github.com/numaproj/numaflow/assets/20961507/e3d4b366-8341-40f2-bb7a-361dc615d8df)

# Use Cases

When would you use this?

To participate in hacktoberfest

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
hi @tczhao, I have added hacktoberfest. Could you please verify?

**Comment by tczhao** [comment]
Hi @vigith , thank you, It looks good
