### ISSUE TITLE
Flaky Numaflow Server API test cases

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1180]
Some of the Numaflow Server API test cases are using string comparison for json output, that could be one of the reasons they became flaky.

```goang
	var clusterSummaryExpect = `{"namespace":"numaflow-system","pipelineSummary":{"active":{"Healthy":2,"Warning":0,"Critical":0},"inactive":0},"isbServiceSummary":{"active":{"Healthy":1,"Warning":0,"Critical":0},"inactive":0}}`
	assert.Contains(s.T(), clusterSummaryBody, clusterSummaryExpect)
```

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by KeranYang** [comment]
Ran current e2e 20 times and did not see it. Closing...
