### ISSUE TITLE
E2E side-input test for Sink

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1193]
Create a new directory called `sink-redis-side-input` at https://github.com/numaproj-contrib/e2e-tests-go

Copy https://github.com/numaproj/numaflow-sinks/tree/main/redis-e2e-test-sink and put it https://github.com/numaproj-contrib/e2e-tests-go

**Comment by vigith** [comment]
is this done?

**Comment by shubhamdixit863** [comment]
> is this done?

Yes it is already merged -https://github.com/numaproj-contrib/e2e-tests-go/tree/main/sink-side-input
PR- https://github.com/numaproj/numaflow/pull/1257 (for both source and sink with sideinputs)
