### ISSUE TITLE
Add RED/Saturation metrics

### ISSUE THREAD

**Issue by Krithika3** [numaproj/numaflow#12]
**Is your feature request related to a problem? Please describe.**
I need to see the RED metrics for my pipeline like Inbound Messages, Outbound messages, Error count etc for my main car and udf side car

**Describe the solution you'd like**
Add the corresponding to prometheus

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
@Krithika3 this is complete, right?

**Comment by Krithika3** [comment]
Yes it is complete
