### ISSUE TITLE
Numaflow e2e pipeline UI fails to load locally after port forwarding

### ISSUE THREAD

**Issue by vaibhavtiwari33** [numaproj/numaflow#1309]
**Describe the bug**
Unable to see the e2e numaflow pipeline locally even after port forwarding the numaflow server

**To Reproduce**

1. port forward the numaflow server to local port
2. `kubectl port-forward svc/numaflow-server 8443`
3. Navigate to `https://localhost:8443/`

**Expected behavior**
Numaflow pipeline should be shown

**Screenshots**
If I port forward the numaflow server using:
`kubectl port-forward svc/numaflow-server 8443`
We get the following error:
![Screenshot 2023-10-31 at 3 57 42 PM](https://github.com/numaproj/numaflow/assets/61685457/7a9cfbde-3ff0-41b4-802c-8719ecabaca9)

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Verified there's no issue in v1.0
