### ISSUE TITLE
expose important metrics via k8s events

### ISSUE THREAD

**Issue by mshakira** [numaproj/numaflow#1326]
# Summary
We need to expose important metrics which are used in triaging via k8s events.

Eg: Controller error stating ISB creation failed 

We also need to revisit all the events emitted. Need to make sure they are tagged in better object (eg pipeline vs vertex)

**Comment by vigith** [comment]
we need to see what is missing, we have few added in #856

**Comment by whynowy** [comment]
Related to #972

**Comment by dpadhiar** [comment]
Working with @mshakira to determine what new events need to be implemented and which currently may need to be adjusted.

List of currently implemented k8s events

Pipeline / pkg/reconciler/pipeline/controller.go 

109 - Warning - ReconcilePipelineFailed - pipeline isn't safe to delete
123 - Warning - ReconcilePipelineFailed - failure to create buffer clean up job
136 - Warning - ReconcilePipelineFailed - non-lifecycle change failures
146 - Warning - ReconcilePipelineFailed - fail to update pipeline phase
151 - Normal - UpdatePipelinePhase
162 - Warning - ReconcilePipelineFailed - non-lifecycle change failures
848 - Normal - ScalingVertex

Vertex / pkg/reconciler/vertex/controller.go 

108 - Warning - ISBSvcNotFound
111 - Warning - FindISBSvcFailed
115 - Warning - ISBSvcNotReady

130 - Warning - BuildPVCSpecFailed
138 - Warning - FindExistingPVCFailed
142 - Warning - CreatePVCFailed

165 - Warning - FindExistingSvcsFailed
176 - Warning - DelSvcFailed
193 - Warning - CreateSvcFailed
203 - Warning - DelSvcFailed

213 - Warning - GetPipelineFailed
219 - Warning - FindExistingPodFailed
225 - Warning - PodSpecGenFailed

294 - Warning - CreatePodFailed
302 - Warning - DelPodFailed

**Comment by whynowy** [comment]
Closed by https://github.com/numaproj/numaflow/pull/1393. Re-open or create a new one if anything else is needed.
