### ISSUE TITLE
Improve ISBSVC and Pipeline Validator

### ISSUE THREAD

**Issue by jy4096** [numaproj/numaflow#1352]

**Comment by KeranYang** [comment]
1. Use IsDNS1053Label to validate the ISBSVC name.
2. Replace gin ShouldBindJson with the json decoder to decode the request body to the spec object. json decoder supports disallowing unknown fields. This catches typos such as `replica`.
3. Disallow updating ISBSVC name and namespace from UI.

https://github.com/numaproj/numaflow/pull/1358
