### ISSUE TITLE
CI should create a stable tag for SDKs 

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1363]
Maybe we should give a tag `stable` for the image, so that we do not need to update it in the test cases.

_Originally posted by @whynowy in https://github.com/numaproj/numaflow/issues/1360#issuecomment-1811925843_

**Comment by KeranYang** [comment]
Adding a formal problem statement... 

Every time we make a change to the SDK, we need to manually rebuild the images under the example folder, and update the image tags under the numaflow test/ folder, such that the e2e test suites can run with the latest SDK changes. It is an operational inefficiency. If we can automate the process, we streamline the development process and also free engineering time to work on innovative tasks.

@a3hadi I am assigning this one to you. We can work on it as the next task.
