### ISSUE TITLE
Enable gofmt check as part of lint CI

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#1374]
# Summary

Currently, our CI doesn't include a format check. Code changes like unsorted imports pass the CI approval workflow. lint supports enabling gofmt. We can enable it to auto-detect the wrong formats. Let's also fix any existing format issues as part of this task.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by a3hadi** [comment]
There were no existing format issues for any of the files based on my testing.

**Comment by KeranYang** [comment]
@a3hadi thanks for making this change, I'm a bit surprised that we didn't find any format issues. Could you execute the following steps to verify this change (if u haven't done so)?
1. pick a .go file and make the import statements unsorted.
2. build the project and verify the build fails the lint step.

**Comment by a3hadi** [comment]
there were no formatting issues, however there were several unsorted imports. i am making those changes right now
