### ISSUE TITLE
Docs: Fix the text size issue for Map and Reduce section

### ISSUE THREAD

**Issue by chandankumar4** [numaproj/numaflow#1378]
**Describe the bug**
Fix the text size issue in [Map](https://numaflow.numaproj.io/user-guide/user-defined-functions/map/examples/) and [Reduce](https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/examples/) section of docs

**Expected behavior**
The text size should be similar to other command line text

**Screenshots**
<img width="2051" alt="Screenshot 2023-11-20 at 6 07 18 PM" src="https://github.com/numaproj/numaflow/assets/28861964/05a01969-9df0-443c-bbae-38371691c8c9">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by boringlyBoring** [comment]
I would be happy to help with the issue. Could you assign this issue to me?

**Comment by whynowy** [comment]
@boringlyBoring - thanks! Assigned.

**Comment by boringlyBoring** [comment]
Thanks! I will start working on it Friday night

**Comment by a3hadi** [comment]
I can pick this up
