### ISSUE TITLE
UI Dex server improvements

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1399]
# Summary

1. The Dex server used for AuthN does not have TLS enabled.
2. There are multiple configuration files need to update (numaflow-cmd-config, dex-config, etc) when enabling Dex. Investigate how to simplify the process. Check how Argo CD does it.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dpadhiar** [comment]
Closed by #1440
