### ISSUE TITLE
UI is not showing Pipeline if you pipeline has autoscaling

### ISSUE THREAD

**Issue by sarabala1979** [numaproj/numaflow#142]
**Describe the bug**
If the vertex scale to 0, UI is failed to show the pipeline on UI. looks like metrics API call is failing.

**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by Krithika3** [comment]
I think Derek fixed this bug. https://github.com/numaproj/numaflow/pull/132/files. Not sure if this is deployed
