### ISSUE TITLE
Kafka source is not sending any data to sink after source vertex pod get crashed due to network issue

### ISSUE THREAD

**Issue by chandankumar4** [numaproj/numaflow#1442]
**Describe the bug**
In case of kafka as source vertex when the `numa` container crashed due to some network issue and once it come back then it's not sending any data to sink vertex

**To Reproduce**

1. Create k3d cluster in local, Reference: https://github.com/numaproj/numaflow/blob/main/.github/workflows/ci.yaml#L171
2. Pull changes of this PR https://github.com/numaproj/numaflow/pull/1412 and checkout to the same.
3. Deploy numaflow in k3d cluster, Reference: https://github.com/numaproj/numaflow/blob/main/.github/workflows/ci.yaml#L181 (you can replace `${{ github.sha }}` with any dummy version for ex: 123)
4. Run sideInput e2e test `KUBECONFIG=~/.kube/numaflow-e2e-config IMAGE_NAMESPACE=k3d-e2e-registry:5111 VERSION=${{ github.sha }} DOCKER_PUSH=true ISBSVC=jetstream make test-idle-source-e2e`  reference: https://github.com/numaproj/numaflow/blob/main/.github/workflows/ci.yaml#L185 (Note: for speed up test you can comment the http source test)
5. Check the data inside redis pod, you can exec into it and check, or replace the redis sink with log{}

Numa container crash log
```bash
{"level":"info","ts":"2024-01-08T15:44:25.178610805Z","logger":"numaflow.Source-processor","caller":"sarama@v1.42.1/sarama.go:129","msg":"Closed connection to broker kafka-broker:9092","pipeline":"kafka-idle-source","vertex":"kafka-in"}
{"level":"panic","ts":"2024-01-08T15:44:25.178843388Z","logger":"numaflow.Source-processor","caller":"kafka/reader.go:414","msg":"Kafka consumer failed with error: ","pipeline":"kafka-idle-source","vertex":"kafka-in","error":"read tcp 10.42.0.43:53770->10.43.75.18:9092: i/o timeout","stacktrace":"github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer.func2\n\t/Users/ckumar14/go/src/github.com/numaproj/numaflow/pkg/sources/kafka/reader.go:414"}
panic: Kafka consumer failed with error:

goroutine 213 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x3?, {0x0?, 0x0?, 0xc000796160?})
	/Users/ckumar14/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000a8e000, {0xc000679ec0, 0x1, 0x1})
	/Users/ckumar14/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc000598fc0, 0x4, {0x24c57e5?, 0x284cc80?}, {0x0?, 0x0?, 0x0?}, {0xc000d07f28, 0x1, 0x1})
	/Users/ckumar14/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xec
go.uber.org/zap.(*SugaredLogger).Panicw(...)
	/Users/ckumar14/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:235
github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer.func2()
	/Users/ckumar14/go/src/github.com/numaproj/numaflow/pkg/sources/kafka/reader.go:414 +0x206
created by github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer in goroutine 200
	/Users/ckumar14/go/src/github.com/numaproj/numaflow/pkg/sources/kafka/reader.go:406 +0x538
```

**Expected behavior**
Redis should be receiving the data in case of kafka pod crash

**Screenshots**
<img width="2055" alt="Screenshot 2024-01-08 at 9 16 13 PM" src="https://github.com/numaproj/numaflow/assets/28861964/887142b5-6d0f-4857-af07-acb4a7b6ebc7">

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.27.4]
- Numaflow: latest

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
we do not see this problem anymore.
