### ISSUE TITLE
SideInput sdk should also write ServerInfo

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1457]
# Summary

This will help on supporting backward compatibility later on.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

```[tasklist]
### Tasks
- [x] Golang
- [x] Python
- [x] Java
- [x] Platform Side Change
```

**Comment by a3hadi** [comment]
I can pick this up

**Comment by KeranYang** [comment]
Re-opening as we need to also make changes on platform side.
