### ISSUE TITLE
UDF doesn't clear the back pressure in case the buffer is full

### ISSUE THREAD

**Issue by inishchith** [numaproj/numaflow#1464]
**Describe the bug**
- Have ran into an issue where the the UDF pod runs into a weird back pressure condition and doesn't recover.

**Problem:** 
- This happens when there was a flood of events flowing (>buffer length - default 30K). The scale spec is set to `min: 1` and `max: 5`  but still the number of pods stays stagnant at 1. There are no errors in the UDF - still there's no recovery from this other than manually scaling up the pods and letting the pressure drop.

**To Reproduce**
Steps to reproduce the behaviour:

- Delete the pipeline
- Reset the consumer group offset
- Re-install the pipeline.

**Expected behaviour**

I would expect a auto-scale up and clearing the back-pressure. The default for a UDF internal error is [retryUntilSuccess](https://numaflow.numaproj.io/user-guide/reference/edge-tuning/#retryuntilsuccess), but in this case there's no UDF errors.

**Screenshots**
![Screenshot 2024-01-17 at 12 57 06 PM](https://github.com/numaproj/numaflow/assets/20226361/16419e02-c351-469d-9d96-b882d17f31bb)
![Screenshot 2024-01-17 at 12 57 38 PM](https://github.com/numaproj/numaflow/assets/20226361/b581e19b-6081-489c-96e9-2035ddd14bca)
![Screenshot 2024-01-17 at 1 10 43 PM](https://github.com/numaproj/numaflow/assets/20226361/5001b64f-e7a8-4484-bdbd-f2ad33df2161)

**Environment (please complete the following information):**

- Kubernetes: v1.24
- Numaflow: v1.1.3

**Additional context**
Have attached logs for the UDF's numa container
[udf-numa-container.log](https://github.com/numaproj/numaflow/files/13968205/udf-numa-container.log)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Did you figure out why the UDF is not processing any message? Autoscaler will not do anything if the processing rate is 0 while there's backlog.

**Comment by vigith** [comment]
I think the cyclic-write is causing a deadlock.

**Comment by inishchith** [comment]
sharing more details:
- there's a cycle for retrying few messages (at max 5 times)
- What I am observing is that - due to the retries, the processing rate is lower as the exit messages which needs to be retries contribute to the input.

**Comment by whynowy** [comment]
I can imagine when attempting to retry, if the buffer is already full, then it will have no way to write the retry message, and it ends up with dead lock.
