### ISSUE TITLE
Create the JS streams concurrently in the Kubernetes job

### ISSUE THREAD

**Issue by kohlisid** [numaproj/numaflow#1479]
# Summary

During the creation of the pipeline we create the buffer streams using the Kube job, we need them to be handled concurrently to speed up the bring up time.

# Use Cases

During init of all pipelines

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
the stream was not getting evenly created hence we added the sleep.

**Comment by whynowy** [comment]
Duplicate with https://github.com/numaproj/numaflow/issues/820
