### ISSUE TITLE
Kafka source panic does not restart the container

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1541]
**Describe the bug**

In Kafka source implementation, if there's any error returned from kafka server side during message consumption, we panic the service intentionally to let the container restart, so that it could start over to initialize the application. However, there are chances that the panic log is seen but the container does not restart, the log shows as below.

```
"panic: Kafka consumer failed with error:
goroutine 358 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x210ca40?, {0x0?, 0x0?, 0xc000e07420?})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002b74ea0, {0xc0046f4500, 0x1, 0x1})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc000491be0, 0x4, {0x25c4562?, 0x2940610?}, {0x0?, 0xc0003d4eb8?, 0xc00011df88?}, {0xc00a607f28, 0x1, 0x1})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
go.uber.org/zap.(*SugaredLogger).Panicw(...)
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:235
github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer.func2()
        /home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:414 +0x225
created by github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer
        /home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:406 +0x54a"
```

**Expected behavior**

The container should restart.

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
I don't think we have resolved this issue yet.

**Comment by vigith** [comment]
This could be causing the idle-source-e2e tests introduced in #1412 to fail.

**Comment by afugazzotto** [comment]
I was unable to reproduce the panic for the idle-source-e2e tests.
