### ISSUE TITLE
Flaky E2E Tests - TestReduceSuite/TestIdleKeyedReducePipeline

### ISSUE THREAD

**Issue by afugazzotto** [numaproj/numaflow#1550]
https://github.com/numaproj/numaflow/actions/runs/8195555528/job/22415020803

**Comment by KeranYang** [comment]
To be fixed by https://github.com/numaproj/numaflow/pull/1412/

**Comment by KeranYang** [comment]
Ran current e2e 20 times and did not see it. Closing...
