### ISSUE TITLE
Flaky e2e test TestSimpleSessionPipelineFailOverUsingWAL

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#1563]
The TestSimpleSessionPipelineFailOverUsingWAL doesn't expect string `1` in the sink but some times we get 2 of it.

example: https://github.com/numaproj/numaflow/actions/runs/8274462313/job/22668313990

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Comment by KeranYang** [comment]
### One Hypothesis

oth `TestSimpleSessionKeyedPipeline` and `TestSimpleSessionPipelineFailOverUsingWAL` share the same pipeline spec. The test sends messages in a way that every 10 seconds, one session window gets materialized. If the pipeline runs forever, every materialized window should output a value of 5.

There is one edge case, when `TestSimpleSessionKeyedPipeline` succeeds, the pipeline gets deleted(EOF), this is when a session window can be closed without reaching 5. The value 1 gets written to the Redis sink and picked up by `TestSimpleSessionPipelineFailOverUsingWAL`, causing the test to fail.

**Comment by KeranYang** [comment]
I will try to verify.

**Comment by KeranYang** [comment]
No, my hypothesis above is not the case. Even running the WAL test individually produces the value 1 with count 2. 

To reproduce: run `make TestSimpleSessionPipelineFailOverUsingWAL` locally several times. @yhl25 thoughts?

**Comment by yhl25** [comment]
I will take a look
