### ISSUE TITLE
Docs: Session Windowing

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#1597]

**Comment by th0ger** [comment]
Hey, until this is doc done, could you give a few words on what session window and reduce streaming of v1.2.*-rc's is about?
Maybe some examples at hand already?

**Comment by yhl25** [comment]
Hey @th0ger

**Session Window**
Session window is a type of Unaligned window. The window's end time continues to shift until no data is received for a specified duration. The window only closes when no data arrives for the specified timeout duration.

![Session Window Diagram](https://github.com/numaproj/numaflow/assets/109710325/b55ef409-faa3-4a74-bd1b-59484e96bcfc)

Examples of Session Window: 
- [Pipeline](https://github.com/numaproj/numaflow/blob/examples/examples/12-simple-session-pipeline.yaml)
- [UDF](https://github.com/numaproj/numaflow-go/tree/main/pkg/sessionreducer/examples)

**Reduce Streaming**
Reduce streaming is the functionality that allows messages to be streamed to the next vertex from the reduce vertex. This is useful for custom triggering, where we want to forward responses to the next vertex quickly, even before the window closes.

Examples of Reduce Streaming: 
- [Pipeline](https://github.com/numaproj/numaflow/blob/examples/examples/13-streaming-reduce-pipeline.yaml)
- [UDF](https://github.com/numaproj/numaflow-go/tree/main/pkg/reducestreamer/examples)

Bare with us! We'll try to finish the doc sooner! :)

**Comment by th0ger** [comment]
Thanks for the clarification and good luck with the upcoming release 👍
