### ISSUE TITLE
Easy way to test Source, SourceTransformer, Map, and Sink in Java

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1625]
# Summary
The way we functional test the Java SDK is to create a local gRPC in-process channel, an input and output stream observer for sending and receiving test data. It's a good use for us as SDK developers but not for users because users shouldn't care about gRPC. We should build a wrapper around gRPC so that we don't expose it to the user.

The ideal way for users to test a Java UDF is that users only take care of implementing the interfaces, invoking a **startServer** function to get the UDF running, and then calling **send** and **receive** to mock input data and verify output data.

An example user test for the mapper function:

```
startSever(new MyMapper());
MapperTestKit.sendMessage(myTestMessage);
Message myTestOutputMessage = MapperTestKit.receiveMessage();
// verify myTestOutputMessage is as expected.
......
```

**NOTE**: We will not be providing a test interface ATM for the Reduce family of functions because it involves more machinery, such as COB, etc.

# Use Cases

Testing integrated from IDEs

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by KeranYang** [comment]
I wrote the summary part and I would like to correct myself. When it comes to unit testing a UDF, we shouldn't even start a gRPC server. A unit test will only interact with the interface the user implements e.g. processMessage() for mapper.

Something like below:

```
testDatum = mock(value, watermark, eventtime, tag, header ...)
outputMessageList = processMessage(testDatum);
verify outputMessageList
```

Naga is working on a concrete example. To be added here.
