### ISSUE TITLE
Seeing duplicate messages in user defined source

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#1633]
```
Duplicate message -  AAAAAJexQqI=-52-input-0  -  419895504
```

we occasionally see around 10 per second.

**Comment by KeranYang** [comment]
Hey @yhl25 , how do we reproduce this issue?

**Comment by yhl25** [comment]
I think this was fixed in - https://github.com/numaproj/numaflow/pull/1613

**Comment by kohlisid** [comment]
Have we observed this again? Or are we good for 1.3 on this to close

**Comment by KeranYang** [comment]
@kohlisid No we haven't. It should be good to close. cc: @yhl25

**Comment by vigith** [comment]
@yhl25 why was this reopened?

**Comment by vigith** [comment]
We do not see this anymore except when there is ack failures due to topic rebalancing.
