### ISSUE TITLE
Offset model does not consider kafka topic name potentially causing wrong dedupe with multi source

### ISSUE THREAD

**Issue by nagarajatantry** [numaproj/numaflow#1637]
https://github.com/numaproj/numaflow-java/blob/main/src/main/java/io/numaproj/numaflow/sourcer/Offset.java#L12-L13

**Comment by KeranYang** [comment]
@nagarajatantry is this regarding a pipeline having multiple udsources and they all read from the same Kafka topic?

**Comment by vigith** [comment]
I think this is when a single source vertex is reading from multiple kafka topics.

**Comment by vigith** [comment]
Today we add vertex name to the message-ID so this won't be a problem.

**Comment by KeranYang** [comment]
Oh cool, I didn't know we could read from multiple topics in a single source. Then, maybe we should change the Offset class to interface like we did in our built-in sources.

**Comment by vigith** [comment]
It is not an issue; in the worst case with multiple topics, the ud-source user can attach the topic name (compose) and later decompose it.
