### ISSUE TITLE
use container-type ENV to name server-info and UDS file

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1666]
Since we cannot have two different container types, we could do as follows.

`${prefix}/numaflow/${UDContainer-type}/server-info`
`${prefix}/numaflow/${UDContainer-type}/uds.sock`

`{$prefix}` could be `/tmp/` or `/var/run/` based on `NUMAFLOW_POD` env var, so it is easy to start the server locally.

**Comment by whynowy** [comment]
Maybe just use the ud container type env existence to determine if it's local or not.

**Comment by kohlisid** [comment]
This is done.
