### ISSUE TITLE
inbuilt JetStream source

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1695]
# Summary

For async processing, a user-defined source (say, a custom HTTP server) could write to JetStream, and Numaflow can reliably process the data. This should be a relatively straightforward pattern since we use JetStream as the ISB. The JetStream source can be an inbuilt source since we already have code for reading and writing to the stream.

# Use Cases

Ability to insert data into the Numaflow pipeline from a decoupled user-defined source.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented, please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by BulkBeing** [comment]
Can you please assign this to me. I can implement this.
