### ISSUE TITLE
Input source deserializer with flatmap functionality

### ISSUE THREAD

**Issue by sarabala1979** [numaproj/numaflow#172]
# Summary

The input source can have a filter functionality to filter the incoming data.

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ashwinidulams** [comment]
we have a usecase for this. as of now, we are using a map immediately after source to accomplish this.
