### ISSUE TITLE
Flaky reduce-two-e2e and idle-source-e2e

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#1727]
reduce-two-e2e - https://github.com/numaproj/numaflow/actions/runs/9034959063/job/24828692966?pr=1723
idle-source-e2e - https://github.com/numaproj/numaflow/actions/runs/9026274446/job/24803315933

**Comment by vigith** [comment]
another instance https://github.com/numaproj/numaflow/actions/runs/9051410913/job/24871041752?pr=1723

**Comment by vigith** [comment]
https://github.com/numaproj/numaflow/actions/runs/9151940689/job/25158694871

**Comment by KeranYang** [comment]
Ran current e2e 20 times and did not see it. Closing...
