### ISSUE TITLE
Status of Numaflow resource should track the status of underlying child resource

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaflow#1774]
# Summary

To truly reflect the status of a Numaflow resource, e.g. ISBService, the underlying status of children `StatefuleSet`.

# Use Cases

User, e.g. numaplane can rely solely on the status of Numaflow resource to truly reflect the overall status including the children.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
It looks like ISBService does in fact have a `phase`. Is it not being reset to `Failed` in the case that the underlying StatefulSet has failed?

**Comment by juliev0** [comment]
This is probably a more generic issue that we need to check if both ISBService and Pipeline will be reset to Failed phase if they become unhealthy and not just at the point that they're being deployed initially (i.e. for Pipeline is there a Vertex in a Failed state? (which requires that Vertex phase take into account the phase of the underlying Pods))

cc @whynowy

**Comment by whynowy** [comment]
I would recommend to check how `StatefulSet` and `Deployment` do. 

`StatefulSet` -> `Pod`
`Deployment` -> `ReplicaSet` -> `Pod`

For us:

`InterStepBufferService` -> `StatefulSet`
`Pipeline` -> `Vertex` -> `Pod`
