### ISSUE TITLE
UI watermarks render on top for multiple input vertices

### ISSUE THREAD

**Issue by th0ger** [numaproj/numaflow#1807]
**Describe the bug**

In the pipeline UI, two vertices are connected with a line (edge). A label above the line states the watermark.

If two or more incoming vertices are connected to the same target vertex, the labels (and lines) render on top of each other making it causing:

1. Impossible to **read the watermark labels** (and visually compare the difference):
![image](https://github.com/numaproj/numaflow/assets/26322144/93f54a1a-b92f-49fd-9fe9-4fec7e9472bd)
1. **Hovering** only works for the "foreground" edge, and its not possible to know which source it belongs to:
![image](https://github.com/numaproj/numaflow/assets/26322144/1da59a68-671a-4e1a-94f3-50e8e5a2a4da)
1. **Clickable areas** for opening sidebar details either ambiguous (when clicked on labels) or extremely hard to click (when clicked on start of edge):
![image](https://github.com/numaproj/numaflow/assets/26322144/dd5db34b-dfff-4da3-8e2c-25f4716bb4ae)
1. **Pending** message *may* have the same issue (in these screenshots I think two "0" rendered on top):
![image](https://github.com/numaproj/numaflow/assets/26322144/87725779-acb9-4160-af1f-da5445bfafaa)

**Expected behavior**
Maybe stack the watermarks vertically or offset the gridpoints where the lines snap to the square vertices.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Comment by th0ger** [comment]
![image](https://github.com/numaproj/numaflow/assets/26322144/e48754b0-50f3-4047-abbb-d2fb7f2ff909)

**Comment by th0ger** [comment]
@veds-g To reproduce, use this "2x2" graph:

```
  edges:
    - from: in1
      to: to1

    - from: in2
      to: to1

    - from: in1
      to: to2

    - from: in2
      to: to2
```

Simple "2-to-1" and "1-to-2" graphs don't show the bug.

**Comment by veds-g** [comment]
@th0ger thanks for the detailed description. I will look into this.
