### ISSUE TITLE
emit received and dropped count metrics

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1861]
# Summary

Today, we do not have information on how many messages have been received and dropped.

# Use Cases

While debugging, why are messages not moving between the vertices?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@samhith-kakarla

**Comment by kohlisid** [comment]
received metric -> are we looking to expose the number of messages read by the vertex or the number of messages that were written to the from buffers?

**Comment by whynowy** [comment]
My understanding received is for read messages, while dropped is for `MessageToDrop`? @vigith - can you clarify?

**Comment by vigith** [comment]
> My understanding received is for read messages, while dropped is for `MessageToDrop`? @vigith - can you clarify? 


That is right

**Comment by kohlisid** [comment]
@vigith So you want a per vertex view of the read messages right?

**Comment by vigith** [comment]
> @vigith So you want a per vertex view of the read messages right?

Read and dropped. I think "read" is already there.

**Comment by kohlisid** [comment]
Yes "read" (per partition -> for each forwarder) exists already.

**Comment by samhith-kakarla** [comment]
Hey it seems there is already a metric in pkg/metrics/metrics.go called "DropMessagesCount" it is being set in udf, sources and reduce in their writeToBuffer functions
