### ISSUE TITLE
Vertex Pod creation failure no reflected in Vertex or Pipeline status

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#187]
When the vertex controller encounters failures on pod creation (such as out of quota), it keeps retrying but does not reflect it in the vertex status, thus it's not clear to the user what's wrong unless checking the controller log.

**Comment by dratler** [comment]
Hi @whynowy ,
is this open for the grab ?

**Comment by vigith** [comment]
@dratler it is yours if you are up for it 😄

**Comment by dratler** [comment]
Hi @vigith ,
I have installed the project locally and now I want to debug it, what is the right\best approach doing it ?

**Comment by dratler** [comment]
Hi @vigith ,
the `k3d` is not working for me but minikube is .
is it valid for development ?
also how can it run it on debug mode ?

**Comment by vigith** [comment]
> the `k3d` is not working for me but minikube is . is it valid for development ? 

It is valid for development but image loading etc. will get tricky. Today `make start` loads the image into `k3d` but if you use `minikube`, you will have to manually load the image. 
Do you know why is `k3d` not working for you?

> also how can it run it on debug mode ?

By default, when you do `make start` in development env, we start the controller in debug mode. This is because `make start` uses this `test/manifests/kustomization.yaml` manifest file.

Also, feel free to join our [slack](https://join.slack.com/t/numaproj/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg) if you feel that will make collaboration easier for you.

**Comment by whynowy** [comment]
This is not an issue - the status has been populated in the Vertex status like following.

```yaml
status:
  lastScaledAt: "2022-10-12T06:19:47Z"
  message: 'pods "simple-pipeline-p1-2-jcgxc" is forbidden: exceeded quota: resource-quota,
    requested: pods=1, used: pods=10, limited: pods=10'
  phase: Failed
  reason: CreatePodFailed
  replicas: 3
```

When querying vertices, it also shows something like below.

```
NAME                     PHASE     REASON            MESSAGE                                                                                                                              DESIRED   CURRENT
simple-pipeline-input    Running                                                                                                                                                          1         1
simple-pipeline-output   Running                                                                                                                                                          1         1
simple-pipeline-p1       Failed    CreatePodFailed   pods "simple-pipeline-p1-2-jcgxc" is forbidden: exceeded quota: resource-quota, requested: pods=1, used: pods=10, limited: pods=10   3         3
```

**Comment by whynowy** [comment]
@dratler - Appreciate your help on getting `minikube` and `podman` supported, please go ahead to refine the PR and get it merged, and pick up more tasks! I'm closing this issue.
