### ISSUE TITLE
User Defined Source

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#19]
**Is your feature request related to a problem? Please describe.**
Similar to User Defined Sink, the users should have the ability to write their own user defined sources without coupling the numaflow code.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by KeranYang** [comment]
Closing this one as it's duplicate with #883
