### ISSUE TITLE
replace JSON format of isb.message with a binary format 

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#204]
Today we have implemented `MarshalBinary` and `UnmarshalBinary` to encode and decode using JSON as the intermediary format. We should try out using binary formats. 

The code change itself is minimal, we should try `encoding/gob` first.

- [ ] Run the performance test before the change (measure CPU usage, TPS, etc.)
- [ ] Make the change
- [ ] Compare the performance

**Comment by vigith** [comment]
This is not a problem for `jetstream` ISB, because we convert to Jetstream format which considers only the `Payload` field (which is already a `[]byte`) of the `Body`. Redis ISB on the other hand passes `Body` which is a `struct` that wraps `Payload`, it uses `MarshalBinary` and `UnmarshalBinary` to covert it to a `[]byte`.

**Comment by xdevxy** [comment]
Clarified with @vigith more, it turned out to be since `Body` only has `Payload` field ATM, we are good to remove the wrapping about `Payload` and directly expose it in `Message`. In this way we won't need to ser/deserialize it, neither the performance benchmark is required.
