### ISSUE TITLE
Possible Regression: pipeline doesn't always drain fully

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#2042]
**Describe the bug**
I took the latest main from Friday ([this](https://github.com/numaproj/numaflow/commit/cf90e258261b50d95db2787cfe23e9008c2ab72a) was the last commit), and see some things that I didn't see with version 1.3.1. Either this is a Regression, or it fixed things which exposed other things that just weren't exposed before.

I am testing a sequence in Numaplane of switching between two versions of a Pipeline. The Pipeline topology changes from one to the other. I also have one vertex which is purposely very slow, so I can observe that it drains fully. 

The way Numaplane works when you switch from version A of a Pipeline to version B is this:

- Numaplane notices that there's a new spec which is different
- Numaplane sets `desiredPhase=Paused`
- Numaplane waits for `status==Paused` (or `Failed`)
- Numaplane modifies the spec to version B, but with `desiredPhase=Paused` still
- Once Numaplane observes that the entire spec change has been reconciled, it updates `desiredPhase=Running`

The behaviors I've seen aren't totally consistent but I've see them often if I go back and forth between version A and B. The two behaviors I've observed:

1. even though vertices are specified to have `scale.min=1`, sometimes after `desiredPhase=Running`, some of the Vertices have replicas=0 (although they are able to scale with load applied)
2. sometimes when `desiredPhase=Paused`, the slow vertex doesn't drain fully but is stopped prematurely

I think in both of these cases I saw this somewhere in the log:
```
{"level":"error","ts":"2024-09-09T03:55:05.854986445Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:161","msg":"Updated desired pipeline phase failed: {error 26 0  rpc error: code = Unavailable desc = error reading from server: read tcp 10.42.0.180:34308->10.43.65.74:4327: read: connection reset by peer}","namespace":"example-namespace","pipeline":"my-pipeline","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:161\ngithub.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-09-09T03:55:05.855064279Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:85","msg":"Reconcile error","namespace":"example-namespace","pipeline":"my-pipeline","error":"rpc error: code = Unavailable desc = error reading from server: read tcp 10.42.0.180:34308->10.43.65.74:4327: read: connection reset by peer","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:85\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```

I can help set up the same environment I have for testing, in conjunction with Numaplane. (I tried a bit doing it with just numaflow and had trouble, which I suspect may be due to timing, as Numaplane is faster than manually executing these changes myself.)

**To Reproduce**

1. Have Numaplane running (I can provide a reliable version and any installation instructions)
2. `kubectl apply -f PipelineRollout1a.yaml` -> observe that Pipeline gets run and doesn't pause since Pipeline is just being created
4. Wait for all Pods to be fully running
5. Port forward http service: `kubectl port-forward svc/my-pipeline-in 8443&`
6. `bash -x ./curl-auto-increment.sh 8443` (this script repeatedly sends an auto-incrementing integer payload at a speed that's higher than the speed of the slow vertex)
7.   Tail the sink log of the Pipeline and observe that the curl script has sent more integers than have gotten to the sink log (these should be drained)
8. `kubectl apply -f PipelineRollout1b.yaml` -> observe that Pipeline goes to "Pausing"
9. It should take the Pipeline a little while to fully drain all the messages through the sink log before the Pipeline reaches "Paused" phase (and sometimes it doesn't (bug 2)). Note that the Pipeline is set to `lifecycle.pauseGracePeriodSeconds: 200` so I'm giving a lot of time for the drain to occur. 
10. Numaplane will update pipeline topology once it's in "Paused"
11. Numaplane will set `desiredPhase=Running` once spec change is fully reconciled (sometimes this results in Vertices that have `replicas=0` (bug 1))
12. Repeat the process going back and forth between `PipelineRollout1a.yaml` and `PipelineRollout1b.yaml`

[pipelines_and_script.zip](https://github.com/user-attachments/files/16925422/pipelines_and_script.zip)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Comment by juliev0** [comment]
> even though vertices are specified to have scale.min=1, sometimes after desiredPhase=Running, some of the Vertices have replicas=0 (although they are able to scale with load applied)

Here's a capture of the numaflow log (in there I show where Numaplane logged something which would have changed the spec of the pipeline), the pipeline while it was in this state of having `phase=Running` yet vertices with 0 replicas, as well as the result of `kubectl get vertex` and `kubectl get vertex -o yaml`

[zero-replicas.zip](https://github.com/user-attachments/files/16925452/zero-replicas.zip)

**Comment by juliev0** [comment]
> sometimes when desiredPhase=Paused, the slow vertex doesn't drain fully but is stopped prematurely

This is the numaflow log I captured for this case (includes some places where I captured what the numaplane log said at that time as it was changing spec). 
[numaflow.log](https://github.com/user-attachments/files/16925457/numaflow.log)

**Comment by juliev0** [comment]
Hey @kohlisid - remember when you were asking for tests that you could try out last week? :) Sorry, I know I didn't give you any. I was trying to not ask you to have to use Numaplane itself, but now I'm thinking it could be helpful ? (since it's hard for me to reproduce otherwise) Maybe if you're available sometime this week (don't mean to interrupt what you're currently working on), I can help set you up with an environment to test with if you don't mind?

**Comment by whynowy** [comment]
Before looking into the detail, but just based on these 2 statements:

1. even though vertices are specified to have scale.min=1, sometimes after desiredPhase=Running, some of the Vertices have replicas=0 (although they are able to scale with load applied)

-> This is possible. The pipeline reconciliation and vertex reconciliation are done asynchronously. `desiredPhase=Running` means the the Pipeline `spec` change, it takes time to reconcile and get to Pipeline `status` change, it take even longer to set the Vertex spec change (updating spec.replicas), and lastly the vertex controller to reconcile to get Vertex `status.replicas` chagne.

2. sometimes when desiredPhase=Paused, the slow vertex doesn't drain fully but is stopped prematurely

-> Was this timeout?

**Comment by juliev0** [comment]
> Was this timeout?

no, I have the `lifecycle.pauseGracePeriodSeconds` set to 200 seconds and it pauses immediately

**Comment by juliev0** [comment]
> This is possible. The pipeline reconciliation and vertex reconciliation are done asynchronously. desiredPhase=Running means the the Pipeline spec change, it takes time to reconcile and get to Pipeline status change (which includes setting the vertex spec.replicas), and lastly the vertex controller to reconcile to get Vertex status.replicas change.

So, in the numaflow log it says:
```
{"level":"error","ts":"2024-09-09T01:33:12.385418563Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:161","msg":"Updated desired pipeline phase failed: {error 26 0  rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.43.65.74:4327: connect: connection refused\"}","namespace":"example-namespace","pipeline":"my-pipeline","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:161\ngithub.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-09-09T01:33:12.385490396Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:85","msg":"Reconcile error","namespace":"example-namespace","pipeline":"my-pipeline","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.43.65.74:4327: connect: connection refused\"","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/Users/jvogelman/GOPATH/src/github.com/numaproj/numaflow/pkg/reconciler/pipeline/controller.go:85\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/jvogelman/GOPATH/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```

And I never see a line that says "currentPhase":"Running"

**Comment by juliev0** [comment]
let me do a little more research on my side before I ask someone else to look at it...

**Comment by juliev0** [comment]
I just reproduced the "not draining" issue. I didn't see the error about not hitting the daemon Pod this time. Maybe that error is really just related to the "zero replica" issue. 

[numaflow.log](https://github.com/user-attachments/files/16936215/numaflow.log)

**Comment by juliev0** [comment]
For the timeout issue, I think there's an issue on both the Numaplane side to only resume the pipeline once daemon is up, and I'm guessing the numaflow side as well as it should be able to eventually handle the `desiredPhase=Running` even if it does receive the request while daemon is down, but if I take care of it on the numaplane side, that would be sufficient as far as Numaplane is concerned.

Numaplane should only resume the pipeline if Numaflow change is fully reconciled, meaning:
1. pipeline.generation=pipeline.status.observedGeneration
2. all children of pipeline are fully reconciled (i.e. pipeline.status.Conditions indicate so)

I can see that on the numaplane side I am specifically look for the `DaemonServiceHealthy` condition Reason != "Progressing", but it appears that instead I am getting this value for the Condition: `{Type:DaemonServiceHealthy Status:False ObservedGeneration:0 LastTransitionTime:2024-09-09 22:30:53 +0000 UTC Reason:GetDaemonServiceFailed Message:Deployment not found, might be still under creation}`

**Comment by juliev0** [comment]
I am going to close this. 

The timeout issue is something I am able to resolve by fixing Numaplane not to try to set desiredPhase=Running until the Daemon (and all children) are fully up.

Once I resolved that one, I don't seem to see the other issue anymore, so perhaps it was somehow caused by the other issue?
