### ISSUE TITLE
Investigate Pipeline and ISBService Child health conditions which could be "Progressing"

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#2053]
# Summary

This is based on [this](https://github.com/numaproj/numaplane/issues/239) Numaplane issue.

Numaplane needs to know which Pipeline and ISBService child health conditions are "progressing", which would indicate that they're still progressing through reconciliation stages, so Numaflow shouldn't unpause pipelines until they're done.

However, there is at least this case which seems to happen during reconciliation, which is not marked as "Reason=Progressing":

`{Type:DaemonServiceHealthy Status:False Reason:GetDaemonServiceFailed Message:Deployment not found, might be still under creation}`

I guess it was probably ambiguous as to whether it was a case of "Progressing" or just general failure?

Can we mark any that might be "Progressing" as "Progressing"? (I am not sure how difficult it is to determine)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
cc @xdevxy

**Comment by juliev0** [comment]
hey @whynowy - sorry for not being clear in the Issue, but this isn't asking to set "phase" at all. This issue is strictly related to the `Condition.Reason`

> you should be able to use a function named IsHealthy to tell that.
That would probably be good.

**Comment by juliev0** [comment]
> you should be able to use a function named IsHealthy to tell that.

Well, really what I’m looking for in this issue is “isProgressing()”

**Comment by whynowy** [comment]
> > you should be able to use a function named IsHealthy to tell that.
> 
> Well, really what I’m looking for in this issue is “isProgressing()”

Honestly, there's no way to tell it is progressing or not, the message `Deployment not found, might be still under creation` is the result of not being able to find the Deployment object, most probably it's because the check happened right after the Deployment is created, and the informer cache hasn't got updated, but we can not arbitrarily say it's progressing.

**Comment by chandankumar4** [comment]
`{Type:DaemonServiceHealthy Status:False Reason:GetDaemonServiceFailed Message:Deployment not found, might be still under creation}`
[This condition](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/pipeline/controller.go#L982) will only occur when it's not able to find the resource, which can be the case during resource creation, where cache isn't get updated and get request is called.

**Comment by juliev0** [comment]
Thanks @chandankumar4 and yeah, I agree with you @whynowy. We can't know one way or the other, so I think another way to handle this within Numaplane is to only concern ourselves with Child Conditions which are unhealthy (in any way, whether it be for `Reason=Progressing`, etc) **after we've begun the PPND process**. I'll go ahead and close this one, and we can just focus on the Numaplane side of things instead.
