### ISSUE TITLE
Yank support for Map Streaming

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2134]
# Summary

We are working on improving the performance of Numaflow by rewriting some underlying elements. While doing that we figured that we should remove [Map Streaming](https://numaflow.numaproj.io/user-guide/user-defined-functions/map/map/#streaming-mode) since it has lot of limitations
* can only do one message at a time
* EOS is not possible because data is already forwarded before the entire computation is over
* error retrying can be done out of the box due to partial data movements.

Reimplement it if need be later on.

> Please comment in this issue if you are using this.

**Comment by QuentinFAIDIDE** [comment]
There is a practical use case for me for these streaming maps.
First the retrying after partial write is okay if the pipeline is idempotent, which should be the goal of any pipeline.
Then, streaming map can be the only solution when a flatmap can take a long time to run.

For example, I got some table indexed by entity, which cover their activity over time. Some entities are services that are used by millions of users and have millions of entries.
I have a map udf that for each entity received, find the activity entries for entities that match specific filters.
Therefore, if I don't have streaming map and receive an input datum for a large entity, first, the max grpc size is likely to be reached and blow up everything, secondly there is no entries going to the next vertices for a few hours if I don't use the streaming map, and my pipeline acts like its frozen.

So for me, even if I am bothered by its sub obptimal perf, if we remove the streaming map, that would break some of my pipelines.

**Comment by vigith** [comment]
thank you @QuentinFAIDIDE, we will **NOT** yank Map Stream.
