### ISSUE TITLE
Show human-readable timestamps in Daemon Service log

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#219]
# Summary
Currently our Daemon Service log shows timestamp in epoch format.

```
{"level":"info","timestamp":1665774352.9100938,"logger":"numaflow","caller":"service/pipeline_watermark_query.go:123","msg":"Head watermark retrieved for vertex cat is -1."}
```
We should change it to human-readable timestamp for a better development experience. An ideal log could be as follow:
```
{"level":"info","timestamp":"Fri, 14 Oct 2022 19:07:16 GMT","logger":"numaflow","caller":"service/pipeline_watermark_query.go:123","msg":"Head watermark retrieved for vertex cat is -1."}
```

What change needs making?
Change logger configuration.

# Use Cases

For developer to easily read logs with clear timestamps.

# When would you use this?
Not urgent.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by akhilchoudhary2k** [comment]
@KeranYang I can work on this issue :)

**Comment by vigith** [comment]
looks like it already prints out the log in human-readable format if we start in DEBUG mode. 
eg., if you set NUMAFLOW_DEBUG to true in a vertex, you will see that the log in human-readable format

**Comment by whynowy** [comment]
The timestamp showing in the log is not supposed for human read, instead it's a standard for log parsing tools.

If you want to see human readable timestamps for debugging, follow the guide https://numaflow.numaproj.io/debugging/ to turn on debug mode, then the timestamp different.

**Comment by whynowy** [comment]
> @whynowy what if we make the default log to have Human readable format instead of epoch ? That might not be necessary but it will enhance the logs right?? I started working on this 😅

When you use `make start` to deploy it on you testing cluster, `debug` mode is already turned on by default.

**Comment by whynowy** [comment]
After discussion with @KeranYang , let me correct what I said:

1. When you run `make start`, debug mode is automatically turned on for the the controller. This does not and should NOT make any change to the vertex pods.
2. To turn on debug mode for vertex pods, follow https://numaflow.numaproj.io/debugging/.
3. For the daemon service pog log, currently there is NO way provided to change the log level, this is something need to enhance. However, this is not the only issue for daemon service pods, there are lot of other things can not be customized, such as replicas, resources, etc, I think we should do that together. 

Based on this, I created a dedicated [issue](https://github.com/numaproj/numaflow/issues/223) for that, and will close this one.

**Comment by KeranYang** [comment]
Thanks Derek and Akhil for diving deep into this issue. I am ok with closing this one as per Derek's comments.
