### ISSUE TITLE
Using custom sinks (golang sdk), the program fails to start

### ISSUE THREAD

**Issue by qianbeibuzui** [numaproj/numaflow#2199]
**Describe the bug**
I am using the latest branch of project main.
After making the image yourself, use the packaged numaflow image.
The use case of 0-isbsvc-jetstream.yaml and the introduction of custom sinks (golang sdk).
**To Reproduce**
1. Latest branch of main
2. Make your own image
3. Yes https://raw.githubusercontent.com/numaproj/numaflow/main/config/install.yaml Modify the image
4. Run the 0-isbsvc-jetstream.yaml case
5. Introduce custom sinks (golang sdk)
**Expected behavior**
Expected custom sinks to print logs like cat links, but fail to start
**Screenshots**
![image](https://github.com/user-attachments/assets/252fec3e-0b4f-42f3-a6bb-500344287571)
![image](https://github.com/user-attachments/assets/93f6ec70-144a-4db7-9197-dc82e59d7de2)
![image](https://github.com/user-attachments/assets/dbe3a066-9bb6-4f3f-9eb3-25ac8d194e29)

pod error
{"level":"error","ts":"2024-11-03T04:50:22.091085715Z","logger":"numaflow.Sink-processor","caller":"jetstream/kv_store.go:170","msg":"Failed to stop","pipeline":"simple-pipeline","vertex":"out","kvName":"default-simple-pipeline-cat-out_OT","watcher":"default-simple-pipeline-cat-out_OT","error":"nats: connection closed","stacktrace":"github.com/numaproj/numaflow/pkg/shared/kvs/jetstream.(*jetStreamStore).Watch.func1\n\t/mnt/e/project/go/demo/numaflow/pkg/shared/kvs/jetstream/kv_store.go:170"}
panic: failed to create sdk client, failed to receive handshake response: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"

goroutine 1 [running]:
github.com/numaproj/numaflow/cmd/commands.Execute(...)
	/mnt/e/project/go/demo/numaflow/cmd/commands/root.go:33
main.main()
	/mnt/e/project/go/demo/numaflow/cmd/main.go:24 +0x3c

**Environment (please complete the following information):**
- Kubernetes: [e.g. v1.24.4-tke.3]
- Numaflow: [e.g. main]

**Comment by kohlisid** [comment]
Hello @qianbeibuzui 
Could you let us know what version of the Golang SDK are you using for your custom sink?

**Comment by qianbeibuzui** [comment]
> 你好@qianbeibuzui 您能告诉我们您在自定义接收器中使用哪个版本的 Golang SDK 吗？

![image](https://github.com/user-attachments/assets/7a46cb47-2178-4dec-b0dc-76ca0090ef70)

**Comment by KeranYang** [comment]
@qianbeibuzui this is a known issue. `numaflow` main is not compatible with `numaflow-go` 0.8.1. Could you try either `numaflow main with numaflow-go main` or `numaflow 1.3.3 with numaflow-go 0.8.1`? Thanks!

**Comment by qianbeibuzui** [comment]
> @qianbeibuzui this is a known issue. `numaflow` main is not compatible with `numaflow-go` 0.8.1. Could you try either `numaflow main with numaflow-go main` or `numaflow 1.3.3 with numaflow-go 0.8.1`? Thanks!

I tried using the main branch of numaflow go and customizing the sink.
A new problem has arisen.

{"level":"error","ts":"2024-11-05T07:48:17.526042529Z","logger":"numaflow.Sink-processor","caller":"sinker/client.go:177","msg":"Received EOT message before all responses are received, we will wait indefinitely for the remaining responses","pipeline":"simple-pipeline","vertex":"out1","received":1,"expected":100,"stacktrace":"github.com/numaproj/numaflow/pkg/sdkclient/sinker.(*client).SinkFn\n\t/mnt/e/project/go/demo/numaflow/pkg/sdkclient/sinker/client.go:177\ngithub.com/numaproj/numaflow/pkg/sinks/udsink.(*UDSgRPCBasedUDSink).ApplySink\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/udsink/udsink_grpc.go:94\ngithub.com/numaproj/numaflow/pkg/sinks/udsink.(*UserDefinedSink).Write\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/udsink/sink.go:79\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).writeToSink.func1\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:390\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:154\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoffWithContext\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:485\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).writeToSink\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:385\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).forwardAChunk\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:264\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).Start.func1\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:140"}

![image](https://github.com/user-attachments/assets/13d9f51d-ac20-43a4-8bcf-2b9f2564eb8a)

**Comment by qianbeibuzui** [comment]
> > @qianbeibuzui this is a known issue. `numaflow` main is not compatible with `numaflow-go` 0.8.1. Could you try either `numaflow main with numaflow-go main` or `numaflow 1.3.3 with numaflow-go 0.8.1`? Thanks!
> 
> I tried using the main branch of numaflow go and customizing the sink. A new problem has arisen.
> 
> {"level":"error","ts":"2024-11-05T07:48:17.526042529Z","logger":"numaflow.Sink-processor","caller":"sinker/client.go:177","msg":"Received EOT message before all responses are received, we will wait indefinitely for the remaining responses","pipeline":"simple-pipeline","vertex":"out1","received":1,"expected":100,"stacktrace":"github.com/numaproj/numaflow/pkg/sdkclient/sinker.(*client).SinkFn\n\t/mnt/e/project/go/demo/numaflow/pkg/sdkclient/sinker/client.go:177\ngithub.com/numaproj/numaflow/pkg/sinks/udsink.(*UDSgRPCBasedUDSink).ApplySink\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/udsink/udsink_grpc.go:94\ngithub.com/numaproj/numaflow/pkg/sinks/udsink.(*UserDefinedSink).Write\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/udsink/sink.go:79\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).writeToSink.func1\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:390\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:154\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoffWithContext\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:485\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).writeToSink\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:385\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).forwardAChunk\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:264\ngithub.com/numaproj/numaflow/pkg/sinks/forward.(*DataForward).Start.func1\n\t/mnt/e/project/go/demo/numaflow/pkg/sinks/forward/forward.go:140"}
> 
> ![image](https://private-user-images.githubusercontent.com/24265428/383057663-13d9f51d-ac20-43a4-8bcf-2b9f2564eb8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDE4MzYsIm5iZiI6MTczMDgwMTUzNiwicGF0aCI6Ii8yNDI2NTQyOC8zODMwNTc2NjMtMTNkOWY1MWQtYWMyMC00M2E0LThiY2YtMmI5ZjI1NjRlYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEwMTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNTM1ZWUxMDdlMDEwMGEzNTViNTY3MWI3NThkZDMwMzY5YThlZTZiYjAxNTUwMDNlNDIyNGQwN2FkMDY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0Ip6sC4nI0KX_qd7E0c6z6_eucxKt2wqFwdMIJJoguI)


I tried updating numaflow to the latest version of the main branch and fixing the issue.

**Comment by KeranYang** [comment]
Thank you @qianbeibuzui for fixing the issue. Please let us know if you have more questions.
