### ISSUE TITLE
Numaflow UI gives "failed to get pod details" on the "Pods View" tab

### ISSUE THREAD

**Issue by chandankumar4** [numaproj/numaflow#2240]
**Describe the bug**

Numaflow UI gives "failed to get pod details" on the "Pods View" tab and getting error in console log of browser as "GET https://localhost:8443/api/v1/metrics/namespaces/default/pods?refreshKey=1732725595999 net::ERR_BLOCKED_BY_CLIENT"

**To Reproduce**

1. Install Numaflow in Kind Cluster, following this guide https://numaflow.numaproj.io/quick-start/
2. Port forwarded Numaflow-server via `k port-forward numaflow-server-546b4f6855-vpvtm -n numaflow-system 8443:8443`
3. Check the "Pod View" of Pipeline

**Expected behavior**

- It should show the detail about Pod

**Screenshots**
<img width="1276" alt="Screenshot 2024-11-27 at 10 15 38 PM" src="https://github.com/user-attachments/assets/073f0db1-3c36-43a2-b071-6c0bd02a20b3">

**Environment (please complete the following information):**

K8s Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.0

- Numaflow: 1.3.3 or 1.4.0

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Comment by vigith** [comment]
@veds-g @adarsh0728 this is a regression please look into this

**Comment by yhl25** [comment]
will be fixed in https://github.com/numaproj/numaflow/issues/2089
