### ISSUE TITLE
Support setting a base href for UX Server

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#229]
# Summary

Add support for overriding the `/` base href for relative links coming back from the UX server.

# Use Cases

When deploying the numaflow UX server behind a reverse proxy at a particular path (i.e. `https://<hostname>/numaflow/`) the inital request succeeds but then subsequent requests fail due to the URL path being incorrect (i.e. browser requests `https://<hostname>/static/js/main.f68bd729.js` when `https://<hostname>/numaflow/static/js/main.f68bd729.js` is what is needed.  Currently there isn't a way to configure a prefix.

Alternatively one can write rules in the reverse proxy to rewrite `/static/...` to `/numaflow/static/...` but that isn't ideal since `static` may not be the only prefix needing to be mapped and also it can conflict with other applications deployed behind the reverse proxy using the same hostname.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
i can work on this

**Comment by whynowy** [comment]
Closed by https://github.com/numaproj/numaflow/pull/228.

**Comment by dseapy** [comment]
@whynowy i don't think this is supported yet.

**Comment by whynowy** [comment]
> @whynowy i don't think this is supported yet.

My bad, I didn't take a close look at this issue, thought it was the one you implemented..

**Comment by dseapy** [comment]
No worries.  Getting back to looking at this now and while I was able to throw together an implementation that mostly works (https://github.com/dseapy/numaflow/commit/058a5ae8788c98ecd0436618e29dd904c06284d7) it doesn't handle BrowserRouter's basename setting, leading to incorrect URLs in the browser when overriding the newly added base-href parameter.  Not sure of an elegant way to set that dynamically though, referenced a SO discussion of various approaches in comment in commit.

While eventually would be nice to be able to deploy under a sub-path, I'm guessing maybe this feature isn't needed by most users at this point and I can make due without it for now using a dedicated hostname.  Maybe can revisit this in the future.

**Comment by whynowy** [comment]
> No worries. Getting back to looking at this now and while I was able to throw together an implementation that mostly works ([dseapy@058a5ae](https://github.com/dseapy/numaflow/commit/058a5ae8788c98ecd0436618e29dd904c06284d7)) it doesn't handle BrowserRouter's basename setting, leading to incorrect URLs in the browser when overriding the newly added base-href parameter. Not sure of an elegant way to set that dynamically though, referenced a SO discussion of various approaches in comment in commit.
> 
> While eventually would be nice to be able to deploy under a sub-path, I'm guessing maybe this feature isn't needed by most users at this point and I can make due without it for now using a dedicated hostname. Maybe can revisit this in the future.

I would recommend to use rewrite rule to achieve it in case somebody has the requirements. We can keep it here and revisit it later.
