### ISSUE TITLE
improve fallback sink doc

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#2302]
We need more details on how to use fallback sink.

1. when to call responseFailure as compared to responseFallback. add it to  https://numaflow.numaproj.io/user-guide/sinks/fallback/
2. how to specify the spec.
* how does `backoff` work with `onFailure` - does it apply to ALL types of onFailure strategies?
add it to https://numaflow.numaproj.io/APIs/#numaflow.numaproj.io/v1alpha1.RetryStrategy
* what are the options for onFailure? 
add it to https://numaflow.numaproj.io/APIs/#numaflow.numaproj.io/v1alpha1.OnFailureRetryStrategy

**Comment by kohlisid** [comment]
https://numaflow.numaproj.io/user-guide/sinks/retry-strategy/
