### ISSUE TITLE
error handling for gRPC reduce (and map) codepath

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#232]
Today, we support only 1 type of error, and that is [gRPC errors](https://grpc.io/docs/guides/error/) (there are no user-defined or initiated errors). 

One could try to use [gRPC retry](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/retry) to retry during an internal error. Looks like, to use this we have to maintain state since we deal with streams which can get seriously tricky if we are to introduce checkpoints.

- [ ] looks into the [gRPC errors](https://grpc.io/docs/guides/error/) and see what errors will affect us
- [ ] check whether [network errors](https://grpc.io/docs/guides/error/#network-failures) are recoverable or not
- [ ] once we have a good idea of the gRPC errors, we need to either implement error handling or we just have to document how we naturally recover

**Comment by vigith** [comment]
One can look into https://github.com/GuyLewin/grpc-bidirectional-streaming-error-handling, a sample code written in Java to simulate corner cases of our server-side stream.

**Comment by ashwinidulams** [comment]
So the proposal is to 

- Have a exception handling mechanism on the server side (in the SDK) that can catch any unhandled errors from udf and set the appropriate grpc status code and a detail with the exception serialized to a utf8 string. 
- On the client side, inspect the error and check 
   -  if its a status error (which indicates that this is a user code error)
   -  if its not a status error, then it could be because the connection got terminated either because of server crashes or a network disruption.
   - have appropriate error translation and propagate status errors to the numa code, retry on communication error to see if the connection can be re-established.

**Comment by vigith** [comment]
Can we extend the error codes to support different kinds of [acknowledgments](https://docs.nats.io/using-nats/developer/develop_jetstream#acknowledging-messages), mainly `NacK` and `Term`? This can help users avoid intentional pod crashing to get it delivered.

Today the field `num_delivered` is managed by ISB, and it gets incremented when we have a numa pod restart causing the `InProgress` routines to be terminated.

**Comment by chromevoid** [comment]
Could we utilize the existing grpc-go retry feature for the numaflow-go client sdk to retry on certain errors https://grpc.io/docs/guides/error/#network-failures?
https://github.com/grpc/grpc-go/blob/master/examples/features/retry/README.md

**Comment by chromevoid** [comment]
> Can we extend the error codes to support different kinds of [acknowledgments](https://docs.nats.io/using-nats/developer/develop_jetstream#acknowledging-messages), mainly `NacK` and `Term`? This can help users avoid intentional pod crash

We could define our own error types in a proto file similar to https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto

**Comment by vigith** [comment]
> We could define our own error types in a proto file similar to https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto

I think custom metadata, etc. are something not all languages support. Writing other SDKs might get tricky.

**Comment by ashwinidulams** [comment]
we can definitely extend the error handling feature to support custom metadata. I will take that up in a different PR.

**Comment by jy4096** [comment]
- [ ] numaflow-python server sdk: return grpc error

- [ ] numaflow-go server sdk: return grpc error (draft PR)

- [ ] numaflow-go client sdk: handle error code and return to sdk caller (draft PR)

- [ ] numaflow-java server sdk: return grpc error TODO

- [ ] numaflow intergration: retry on retryable errors and gracefully exit on non-retryable errors TODO
