### ISSUE TITLE
Unary gRPC message size limit 4MB

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#237]
# Summary

There's a 4MB message size limit for unary gRPC message size, this is going to impact:

1. UDSink, which always do batch requests;
2. UDF which has single message over 4MB.

We need to fix this in 2 steps:

- [x] #299
- [x] #335

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by shashank10456** [comment]
I would like to contribute to this.
