### ISSUE TITLE
Can not write data to ISB

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#244]
**Describe the bug**
Saw following error in a Kafka source, and pod restart couldn't help. JetStream version is `v2.9.1`, nats client version `v1.6`. 

This error means data written to JetStream has no response, and can not see the new data from nats console.

Suspect it might be caused by too old version of client.

```
{"level":"error","ts":1666283232.9209442,"logger":"numaflow.source-processor","caller":"forward/forward.go:350","msg":"Retrying failed msgs","vertex":"devx-odl-mds-gcp-kafka-source","errors":{"nats: stalled with too many outstanding async published messages":500},"stacktrace":"github.com/numaproj/numaflow/pkg/isb/forward.(*InterStepDataForward).writeToBuffer\n\t/home/runner/work/numaflow/numaflow/pkg/isb/forward/forward.go:350\ngithub.com/numaproj/numaflow/pkg/isb/forward.(*InterStepDataForward).writeToBuffers\n\t/home/runner/work/numaflow/numaflow/pkg/isb/forward/forward.go:308\ngithub.com/numaproj/numaflow/pkg/isb/forward.(*InterStepDataForward).forwardAChunk\n\t/home/runner/work/numaflow/numaflow/pkg/isb/forward/forward.go:245\ngithub.com/numaproj/numaflow/pkg/isb/forward.(*InterStepDataForward).Start.func1\n\t/home/runner/work/numaflow/numaflow/pkg/isb/forward/forward.go:119"}
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.21.6]
- Numaflow: [e.g. v0.5.5]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
are we still seeing this issue?
