### ISSUE TITLE
make test fails when jetstream server is not running

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#256]
**Describe the bug**

Jetstream required for unit tests but not documented as required tool.

**To Reproduce**

1. Install the required tools - https://github.com/numaproj/numaflow/blob/main/docs/development.md#install-required-tools
2. Run `make test`
3. Failed test with the following output:
```
    processor_manager_test.go:35: 
        	Error Trace:	processor_manager_test.go:35
        	Error:      	Received unexpected error:
        	            	failed to connect to nats url=nats://127.0.0.1:4222: nats: no servers available for connection
        	Test:       	TestFetcherWithSameOTBucket
--- FAIL: TestFetcherWithSameOTBucket (0.00s)
```

**Expected behavior**
`make test` to pass

**Environment (please complete the following information):**

- Kubernetes: N/A
- Numaflow: head of main

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
I'm happy to take this one.

Seems like either adding `jetstream` to the `Install required tools` would be sufficient.  Alternatively the following also seems to work which does not require a server be running locally (it does require adding `github.com/nats-io/nats-server/v2` to `go.mod`):

```golang
import (
       "github.com/nats-io/nats-server/v2/server"
       natsServer "github.com/nats-io/nats-server/v2/test"
)
```
```golang
       // Run NATS server
       opts := &natsServer.DefaultTestOptions
       opts.Port = server.RANDOM_PORT
       opts.JetStream = true

       nServer := natsServer.RunServer(opts)
       defer nServer.Shutdown()

       natsJetStreamUrl := fmt.Sprintf("nats://%s", nServer.Addr().String())
```

**Comment by whynowy** [comment]
Somebody commented out https://github.com/numaproj/numaflow/blob/main/pkg/watermark/fetch/processor_manager_test.go#L1 by accidentally, remove the `//` to fix it.
