### ISSUE TITLE
nil pointer dereference when running 1-simple-pipeline with minimal crd

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#260]
**Describe the bug**
When installing with a namespaced mode it is suggested that user should use minimal crd (ref: https://github.com/numaproj/numaflow/blob/29f15d57a125c54b6de8c4cd29d16e3d8473b655/docs/installation.md#namespace-scope).  When doing this the `simple-pipeline` example (ref: https://github.com/numaproj/numaflow/blob/27e6a8755bd1092b31d93fac891d1decd006a093/examples/1-simple-pipeline.yaml) errors with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a66f29]

goroutine 1 [running]:
github.com/numaproj/numaflow/pkg/sources.(*SourceProcessor).getSourcer(0xc0009a7d78, {0xc0001abd80, 0x1, 0x1}, {0x23b7b80, 0xc0005ee690}, 0x23b2100?, {0x23b7bd0, 0xc0007f82e0}, 0xc000493b70)
	/home/dseapy/github/numaflow/pkg/sources/source.go:145 +0x4c9
github.com/numaproj/numaflow/pkg/sources.(*SourceProcessor).Start(0xc0009a7d78, {0x23cc038, 0xc0001e83f0})
	/home/dseapy/github/numaflow/pkg/sources/source.go:95 +0x465
github.com/numaproj/numaflow/cmd/commands.NewProcessorCommand.func1(0xc00059f680?, {0x2076944?, 0x2?, 0x2?})
	/home/dseapy/github/numaflow/cmd/commands/processor.go:67 +0x525
github.com/spf13/cobra.(*Command).execute(0xc00059f680, {0xc000130fe0, 0x2, 0x2})
	/home/dseapy/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x33a1440)
	/home/dseapy/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/dseapy/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/numaproj/numaflow/cmd/commands.Execute()
	/home/dseapy/github/numaflow/cmd/commands/root.go:16 +0x25
main.main()
	/home/dseapy/github/numaflow/cmd/main.go:8 +0x17
```

This is caused due to `msgSize` missing in the example, which doesn't get defaulted when using minimal crd.

**To Reproduce**

1. Install minimal crd in cluster
2. kubectl apply the `1-simple-pipeline.yaml` example
3. kubectl logs the `simple-pipeline-in-0-...` pod

**Expected behavior**
* Error message provides indication as to what is missing.
* Warning in installation guide that full crd leverages defaults which will not be populated by the minimal crd.  Therefore some examples may be incomplete if using the minimal crd.

**Environment (please complete the following information):**

- Kubernetes: v1.25.3
- Numaflow: head of main

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
I can work on this

**Comment by vigith** [comment]
interesting, we do provide a default, https://github.com/numaproj/numaflow/blob/main/pkg/apis/numaflow/v1alpha1/generator_source.go#L15

**Comment by dseapy** [comment]
> interesting, we do provide a default, https://github.com/numaproj/numaflow/blob/main/pkg/apis/numaflow/v1alpha1/generator_source.go#L15

yeah, i think make manifests throws it in the full crd, but then any defaults don't survive the creation of the minimal crd (https://github.com/numaproj/numaflow/blob/27e6a8755bd1092b31d93fac891d1decd006a093/hack/crdgen/crd.go#L32).
