### ISSUE TITLE
Reduce or document watermark ignored pod logs in simple pipeline

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#266]
# Summary

Currently when running simple-pipeline from https://github.com/numaproj/numaflow/tree/main/examples#numaflow-by-example it prints out lots of logs in all the vertex pods that look like the following:
```
{"level":"info","ts":1666688845.801714,"logger":"numaflow.udf-processor","caller":"publish/publisher.go:88","msg":"New watermark is ignored because it's older than the current watermark","vertex":"simple-pipeline-cat","head":"2022-10-25T09:07:24Z","new":"2022-10-25T09:07:24Z"}
```

It's not clear if it's expected to get all these messages or if it's an issue.  I think since they are logged at `info` rather than `debug` or `warn` it's not clear if it's a problem or something I can ignore.  I'm not sure the best thing to do, but maybe one of the following:

* Consider changing the log level if it makes sense
* If it's something new user is likely to be seeing a lot in the logs, add documentation either in the examples' README.md or in the docs' watermarks.md.  `1-simple-pipeline-wm-disabled.yaml` prevents the additional logs, but watermarks are enabled on the readme example.

# Use Cases

When getting started with examples it would be nice if the logs were cleaner to be sure install went smoothly.  It would also make seeing the other logging (i.e. `2022/10/25 09:30:51 (out) {"Data":"Cv52GfRFIRc=","Createdts":1666690251805359626}`) easier without relying on something like `| grep -v older` on kubectl logs.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
i'm happy to make whatever changes (if any) make sense to do for this

**Comment by vigith** [comment]
```json
{"level":"info","ts":1666688845.801714,"logger":"numaflow.udf-processor","caller":"publish/publisher.go:88","msg":"New watermark is ignored because it's older than the current watermark","vertex":"simple-pipeline-cat","head":"2022-10-25T09:07:24Z","new":"2022-10-25T09:07:24Z"}
```

the above logs are a symptom of a few other things about watermark progression. Ideally you should see very few of these messages. #251 is related to this. We will also move to millisecond progression, which will reduce the time collision #201

**Comment by vigith** [comment]
are you seeing this problem even with a single tickgen pod (source vertex == 1)?

**Comment by vigith** [comment]
Let me ask @chromevoid to look into this ask she is looking into the other two issues.

**Comment by vigith** [comment]
@chromevoid, let's look into this after we resolve #201. It could be that, we store watermark is stored at seconds granularity and we have more requests in the same second.
