### ISSUE TITLE
AWS SQS source and sink

### ISSUE THREAD

**Issue by edlee2121** [numaproj/numaflow#30]
**Is your feature request related to a problem? Please describe.**
Would be useful to be able to source events from AWS SQS.

**Describe the solution you'd like**
A source that turns GCP Pub/Sub events into messages for further processing.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
@shubhamdixit863 once you complete the issues listed in https://github.com/numaproj-contrib/aws-sqs-source-go/issues, please go ahead and close this.

**Comment by vigith** [comment]
Completed! [SQS Source](https://github.com/numaproj-contrib/aws-sqs-source-go) and [SQS Sink](https://github.com/numaproj-contrib/aws-sqs-sink-go)
