### ISSUE TITLE
Too many keys in Offset Timeline bucket causing slowness in watch and publisher startup

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#301]
The watermark publisher publishes a key-value pair where the key is the timestamp, and the value is the offset. This has a space complexity of O(N) even though we garbage-collect the data. This is a big problem for a high TPS (e.g., 10K TPS) input where we end up with 10s of thousands of key-value pairs, which have to be read on start-up of a processing unit and also have to be tracked via `Watch`.

Instead of having a new key-value pair for every timestamp and offset, we will have a single key for each processing unit, and the value will be a timestamp and offset pair. This means we will be rewriting the value every time there is a new update for that processing unit. This approach only has a space complexity of O(const) (number of processing units). The new approach will be more efficient also as we can have the value represented as binary.

We can use the `Watch` on the bucket for every overwrite of the value of the static key. With static keys, if the consumer (i.e., the fetcher) has to look back at a few older timelines, it can rely on the `History` feature of the store, where it can store up to 64 revisions. We only need 2 revisions, but we can keep up till 5 (can be configurable). 

E.g,
```go
map[string]struct{
  watermark int64, 
  offset int64
} {
  "pod1": { 
     watermark: 1667326389000, 
     offset: 12345 
  }
}
```

**Comment by vigith** [comment]
First, remove the individual bucket support in OT. Since we are going with a constant key approach, we will never need individual OT buckets.

**Comment by KeranYang** [comment]
> The new approach will be more efficient also as we can have the value represented as binary.

@vigith If I understand correctly, having the value represented as binary will save memory for the KV store, hence also helpful in terms of being more efficient?

Would it become less convenient from a developer's perspective when it comes to debugging? As we will now see binary values when inspecting JetStream kv store and need to manually decode to see the actual watermark epoch.

**Comment by chromevoid** [comment]
We have debug level logs. 

We don’t usually directly check JetStream for debugging. Also, for the original design, the value (offset) in JetStream is encoded in binary too… meaning, no matter which design we use, if we want to directly check JetStream kv store data, we always need to decode the value…

**Comment by vigith** [comment]
> Would it become less convenient from a developer's perspective when it comes to debugging? As we will now see binary values when inspecting JetStream kv store and need to manually decode to see the actual watermark epoch.

I am wondering whether we should give some utility CLI tools in the future to inspect and debug our platform. E.g., with the introduction of WAL, we need to inspect that store, which has data in binary format.
