### ISSUE TITLE
Allow setting container resource limits and requests on init containers

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#303]
# Summary

Currently `init` containers use `standardResources` defined in the code, with `numa` containers either defaulting to `standardResources` or not being set.  `numa` containers are override-able using `containerTemplates`.

Allowing users to configure the `init` container resources is useful.  A couple possibilities:
1. setting `standardResources` value, i.e. controller configmap
2. setting overrides in the k8s custom resources

# Use Cases

When deploying in namespaces with a `ResourceQuota` requiring memory limits or cpu limits be set on all containers, the pods don't run.  ResourceQuota may be set for restricting resources on namespace but also enforcing memory limits are set (i.e. https://twitter.com/thockin/status/1134193838841401345?lang=en)

A workaround is setting a `LimitRange` default in the namespace to populate limits on containers that do not specify them. 
The issues with this are:

1. This affects more containers than just the numaflow containers, so when sharing a namespace with non-numaflow pods this will affect those pods.
2. It can lead to over-provisioning since the `LimitRange` default must be as high as the container with the most resource need that doesn't specify resources.
3. Limit ranges don't have visibility into what is already set in container resources, potentially leading to unexpected behavior ("A LimitRange does not check the consistency of the default values it applies." - https://kubernetes.io/docs/concepts/policy/limit-range/#limitrange-and-admission-checks-for-pods).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
I can work on this one assuming it makes sense to do.  If preferred not make it configurable, setting memory limit for `standardResources` would also be sufficient for my current use-case.  If making it configurable is good, then not sure at the moment the preferred place to configure but can throw up a solution & discuss on a PR if changes should be made.

**Comment by vigith** [comment]
+1 on making it configurable. @whynowy WDYT?

**Comment by dseapy** [comment]
went ahead and threw up a quick PR as a possible implementation.  no worries through if it's not what's desired, had some free time & felt like writing up some code.
