### ISSUE TITLE
Support adding sidecar containers in udf vertex pods

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#323]
# Summary

Allow the user to specify a list of containers to add to the vertex pods, similar to how init-containers can currently be provided.

# Use Cases

Certain java libraries are useful for some specialized processing needing to be done.  Would like to make those capabilities available to python udf containers written by data-scientists via an apache arrow flight (GRPC) API. Would like to avoid calling out to another pod & instead have a shared volume between the containers for this use-case as some data is quite large.

Another thing that would be nice to do is collect more custom metrics related to cost/gpu-usage.  Having a minimal sidecar container written in Go maintained by devops would be useful.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
This is a good feature, e.g., in operational data analytics where we rely on [apache-datasketches](https://datasketches.apache.org/), which has first-class support for Java. A sidecar will help golang or python SDKs access the Java libraries.
