### ISSUE TITLE
Add Pipeline pausing docs

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#333]
# Summary

Just learned you can scale down an entire pipeline with paused when looking through repo, which is super useful.  don't think it's in the docs yet, might be good to add

# Use Cases

user wanting to pause a pipeline might not know it's a supported feature.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
That's right, hidden features :-)
