### ISSUE TITLE
switch to stream mode for UDSink

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#335]
We have to switch to stream mode for UDSink, like reduce. For the stream to be closed, make sure we close the stream once we have written all the elements in the batch to the stream.

- [x] https://github.com/numaproj/numaflow-go/pull/25
- [ ] https://github.com/numaproj/numaflow/pull/421
- [x] https://github.com/numaproj/numaflow-python/pull/34
- [x] https://github.com/numaproj/numaflow-java/pull/8

**Comment by shashank10456** [comment]
I would like to contribute to this.
