### ISSUE TITLE
NATS Source

### ISSUE THREAD

**Issue by pitwegner** [numaproj/numaflow#355]
# Summary

It would be nice to not only have Kafka and Webhooks as streaming sources, but also NATS. JetStream is already used as a buffer between the vertices, so why not add it as a source?

# Use Cases

We'd like to use Numaflow in combination with our existing NATS engine without having to deploy Kafka and a Kafka-NATS bridge.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@pitwegner - curious, you were asking for `nats` or `jetstream` source?

**Comment by dkdndes** [comment]
@whynowy I assume nats, the reference mentions Jetstream only

**Comment by pitwegner** [comment]
@whynowy @dkdndes correct, this refers to NATS as a source.
