### ISSUE TITLE
Numaflow UI access path

### ISSUE THREAD

**Issue by martiningka** [numaproj/numaflow#375]
# Summary

What change needs making?

I need to be able to access the UI under path different than the root path ("/")

# Use Cases

When would you use this?

I'm installing numaflow in a k8s cluster and I need to access the numaflow UI under <some_host>/numaflow. The current implementation makes this impossible for me, since I can create a k8s ingress for <some_host>/numaflow but not directly to <some_host>

---

**Message from the maintainers**:
It will be nice if you enhance BrowserRouter(index.tsx) with PUBLIC_URL environment variable
`<BrowserRouter basename= { process.env.PUBLIC_URL } >` 

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dseapy** [comment]
in case it's helpful I did some initial work [here](https://github.com/dseapy/numaflow/commit/058a5ae8788c98ecd0436618e29dd904c06284d7) 
 for https://github.com/numaproj/numaflow/issues/229

**Comment by whynowy** [comment]
@dseapy - would you mind raising a PR with your code change?

**Comment by dseapy** [comment]
> @dseapy - would you mind raising a PR with your code change?

done, put it up as a draft PR. have had other higher priority tasks recently, so haven't had a chance to work on fixing the browserrouter issue yet.

**Comment by louisnow** [comment]
@whynowy @dseapy Will we merge the feature to main sometime? This is very useful to avoid having to spin up something like nginx just to change the base path
