### ISSUE TITLE
handling early return from reduce

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#459]
```go
for data := range reduceCh {
         
		err := f(data.Value())
		if err != nil {
			return functionsdk.MessagesBuilder().Append(functionsdk.MessageToDrop())
		}
	}
```

in case if the user wrongly writes the code like above, the reduceCh will be blocked for write as nobody is consuming.
We as a platform should be able to handle early returns even though it's not the right approach.

The map counterpart for this issue is https://github.com/numaproj/numaflow/issues/623

**Comment by vigith** [comment]
The map counterpart for this issue is #623

**Comment by vigith** [comment]
We can return partial responses but draining the channel is required for correctness.
