### ISSUE TITLE
revisit whether we need bi-directional streaming for reduce

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#509]
`ResourceExhausted desc = trying to send message larger than max (19144763 vs. 4194304)`

This is because today we demultiplex at client side because we create single gRPC stream from `numaflow`.

```
ERROR 2023-01-25 15:16:08 {"level":"error","ts":1674639968.7128754,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:129","msg":"Process failed","vertex":"osam-metrics-sliding-aggregation","partitionID":"1674639300000-1674639900000","error":"gRPC client.ReduceFn failed, failed to execute stream.CloseAndRecv(): rpc error: code = ResourceExhausted desc = trying to send message larger than max (19144763 vs. 4194304)","stacktrace":"github.com/numaproj/numaflow/pkg/reduce/readloop.(*orderedForwarder).reduceOp\n\t/Users/adulam/intuit-work/analytics/numaflow/pkg/reduce/readloop/ordered.go:129"}
```

- [x] #549
- [ ] sdk changes
- [ ] #552

**Comment by whynowy** [comment]
My understanding is the 4MB size limit is on each received message, not the whole, am I wrong?

**Comment by whynowy** [comment]
I see, you are talking about the client side received message.

**Comment by vigith** [comment]
> I see, you are talking about the client side received message.

yes, it is the gRPC client (numaflow) that is getting result from the UDF (gRPC Server)
