### ISSUE TITLE
Idle watermark design doc [document]

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#516]
# Summary

Today, the watermark only can be propagated when there's data moving to the branches of a pipeline, we need to figure out how to make the watermark keeps propagating even when there's no data going to that branch (conditional forwarding, reduce with keyed windowing).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by chromevoid** [comment]
https://github.com/numaproj/numaflow/issues/480
