### ISSUE TITLE
Support Redis stream as source and sink

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow#525]
# Summary

What change needs making?
- Adding Redis stream as source for Numa flow pipeline

# Use Cases

When would you use this?
- We are using Redis stream as inter step buffer, can we also add Redis stream as source and sink? That will simplify our infrastructure set up and application code.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
@whynowy can you assign this to me?

**Comment by juliev0** [comment]
Note from Vigith and Derek: start with source, sink is TBD due to 1. users can define sinks fairly easily; 2. supporting many different variations of the sink

**Comment by juliev0** [comment]
So, the way this was implemented, each Key and Value becomes a single message (whose value is the Value and whose key is the Key). Is this what you were looking for, or did you need for a single incoming message with multiple keys/values to result in a single published Message (say a json-serialized Message) with no Key?

If this is desired, I can look at making it configurable.

**Comment by juliev0** [comment]
> So, the way this was implemented, each Key and Value becomes a single message (whose value is the Value and whose key is the Key). Is this what you were looking for, or did you need for a single incoming message with multiple keys/values to result in a single published Message (say a json-serialized Message) with no Key?
> 
> If this is desired, I can look at making it configurable.

Discussed internally and it seems reasonable that a user would want to keep that set of keys/values collocated. One proposal is this:
_if there is only 1 message then key and value are separated else key will be none and value will be an array of key, value pairs_

Or otherwise it can be configurable. Please let me know if any users who are interested in Redis Streams source have an opinion about this, thanks!

**Comment by juliev0** [comment]
Added enhancement issue: https://github.com/numaproj/numaflow/issues/662
