### ISSUE TITLE
Allow sending message back to the vertex itself

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow#622]
# Summary

What change needs making?
Allow the message to be sent to the vertex itself.

# Use Cases

When would you use this?

When the vertex failed to process, we like to retry a few times before abort. Sometimes we can do the retry within the code, but for example when the nodes/pods has an issue with resources, maybe rescheduling that message on another pod which run on another node could help.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
Will not ack-ing the message do the trick?

**Comment by sandangel** [comment]
You mean throwing error and exit that program right? i think it will work but won't be a good way to represent the great capabilities of numaflow. 😀

**Comment by vigith** [comment]
If we have #538 then won't it be possible not to just ack with out restarting?

**Comment by sandangel** [comment]
@vigith could you give me some pseudocode with #538 implemented?

this is my version:

```python
def __main__() -> None:
        grpc_server = UserDefinedFunctionServicer(
            map_handler=run,
        )
        grpc_server.start()
        
def run(_: str, d: Datum)-> Messages:

        mc = MyClass(**json.loads(d.value))
        if mc.retries > 5:
            return Messages(Message('', b'').to_drop())
        try:
            // ...
        catch Exception:
            mc.retries += 1 // won't need anymore after #538?
            return Messages(Message(...).to_self())

```

**Comment by vigith** [comment]
I get your point, we used to support the signature that allowed the user to return an error `def run(_: str, d: Datum)-> (Messages, error)`. 

Perhaps we just need to add that back as a new function, and call it `MapWithError`.

**Comment by vigith** [comment]
Why is not crashing not a good idea? The reason why we propose crashing is that if the container is misbehaving, what is the point of keeping that container alive?

**Comment by sandangel** [comment]
```python
def __main__() -> None:
        grpc_server = UserDefinedFunctionServicer(
            map_handler=run,
        )
        grpc_server.start()
        
def run(_: str, d: Datum)-> Messages:

        mc = MyClass(**json.loads(d.value))
        if mc.retries > 5:
            return Messages(Message('', b'').to_drop())
        try:
            // ...
        catch Exception:
            mc.retries += 1 // won't need anymore after #538?
            raise AssertionError("Program is crashing, won't acknowledge the message")
```

> the point of keeping that container alive?

that is a good point. I was just thinking that the meaning of sending to the vertex itself is a clear intention of retrying steps that failing. While `raise Exception mean the program is running into a bad state, and that's all. If you are not familiar with numaflow and you look at that code, it's hard to tell that `raise AssertionError` means retrying.

**Comment by sandangel** [comment]
But I guess #538 could also solve this problem as you mentioned. I can `raise` error in python code. Not sure what should we use in golang code yet.

**Comment by vigith** [comment]
I think it is a matter of good documentation. What do you think?

**Comment by sandangel** [comment]
I think we can go with it for now. Let me bring it to our team first, and let you know if they have any arguments on this. thanks for taking time to consider. 🙇🏼‍♂️

**Comment by sandangel** [comment]
But #538 I think it's a crucial feature to handle our retry and error handling, skipping message.

**Comment by vigith** [comment]
We will prioritize #538
