### ISSUE TITLE
Incorrect processing rate on source vertex

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#624]
**Describe the bug**

The processing rate on a source vertex is calculated by checking the offset changes on the 1st write buffer, it used to work well because a source vertex was not allowed to connect to a reduce vertex, or do conditional forwarding. With source transformer supported, those restrictions are not there any more, it makes the processing rate calculation incorrect.

- [x] Design doc
- [x] Autoscaling with metrics

**Comment by vigith** [comment]
will this affect the auto-scaling?

**Comment by KeranYang** [comment]
Closed by
#743 
#758 
#761
