### ISSUE TITLE
Flaky unit test TestNewInterStepDataForward_dropAll

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#646]
**Describe the bug**
https://github.com/numaproj/numaflow/actions/runs/4556204235/jobs/8036292310
https://github.com/numaproj/numaflow/actions/runs/4547567391/jobs/8017614440

**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by KeranYang** [comment]
Notes: to make it consistent, just add `time.Sleep(time.Second)` before `assert.Equal(t, true, to1.IsEmpty())`.

**Comment by chromevoid** [comment]
> Notes: to make it consistent, just add `time.Sleep(time.Second)` before `assert.Equal(t, true, to1.IsEmpty())`.

I just updated this test in the https://github.com/numaproj/numaflow/pull/627
after we've introduced wmb and ctrl message, the buffer actually should contain one control message, not empty
