### ISSUE TITLE
Redis Streams Source should implement "Pending" function

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#651]
# Summary

We can do Autoscaling of a Redis Streams Vertex if we implement the Pending() function. This function will return the number of messages pending for the entire ConsumerGroup.

Can probably call `XINFO GROUPS <stream>` from [here](https://redis.io/docs/data-types/streams-tutorial/) and use "lag".

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
Is this possible in 6.x redis? I thought it was available on in 7.x.

**Comment by juliev0** [comment]
Actually, are you referring to the version of server or client? For the source, if the user is providing the Redis installation does it matter to us?

**Comment by vigith** [comment]
I am talking about the server version.

**Comment by juliev0** [comment]
> I am talking about the server version.

In that case, I guess we can support this if the Redis Source they're using is >=7.x.

**Comment by juliev0** [comment]
When testing with versions < 7, I noticed that the Lag reported is 0. 

Decision by @whynowy is that we will therefore require versions >= 7. So, the plan will be to convert our existing Redis 6 ISBSVC into Redis 7 before implementing this.
