### ISSUE TITLE
improve CompareSlice space and time complexity

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#672]
@yhl25 Please consider my proposal of saving time complexity by adding space complexity (GoLang GC periodically reclaims the allocated memory).

`CompareSlice` is on a frequent path that every message goes through it hence its performance matters.

_Originally posted by @KeranYang in https://github.com/numaproj/numaflow/pull/668#discussion_r1164354329_

**Comment by dpadhiar** [comment]
Working with @KeranYang last week, we have found that multiple different approaches to improve the space and time complexity of the CompareSlice function from O(n*n) to O(n) time and O(n) space has not been successful. This was tested with benchmarks, below are the method and results:

Current approach:
```
go test -bench=. -benchtime=60s -run=^#
goos: darwin
goarch: amd64
pkg: github.com/numaproj/numaflow/pkg/shared/util
cpu: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
BenchmarkCompareSlice-8         1000000000               9.648 ns/op
PASS
ok      github.com/numaproj/numaflow/pkg/shared/util    11.072s
```

Hashset approach:
```
go test -bench=. -benchtime=60s -run=^#
goos: darwin
goarch: amd64
pkg: github.com/numaproj/numaflow/pkg/shared/util
cpu: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
BenchmarkCompareSlice-8         1000000000              66.77 ns/op
PASS
ok      github.com/numaproj/numaflow/pkg/shared/util    73.006s
```

Sorting both slices before comparison approach:
```
go test -bench=. -benchtime=10s -run=^#
goos: darwin
goarch: amd64
pkg: github.com/numaproj/numaflow/pkg/shared/util
cpu: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
BenchmarkCompareSlice-8         50784166               230.0 ns/op
PASS
ok      github.com/numaproj/numaflow/pkg/shared/util    12.359s
```
