### ISSUE TITLE
Support running as non-root user

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow#688]
# Summary

What change needs making?

Currently numaflow is running as root

# Use Cases

When would you use this?

The cluster is enforcing running container as non-root, but there is an issue with numaflow when running as non-root. It was not able to write to mounted volumes, even though securityContext fsGroup is set.

More info: https://numaproj.slack.com/archives/C03GQ3AMHE1/p1681546238208929

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Errors.


{"level":"warn","ts":1681541906.1529396,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681541914.2472534,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681541926.675691,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681541944.6003408,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681541971.6624436,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681542011.7481785,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681542070.4809866,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681542163.8523812,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681542298.4298596,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"warn","ts":1681542501.7024734,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"info","ts":1681542675.8147438,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/processor_manager.go:184","msg":"v.AddProcessor successfully added a new fromProcessor","vertex":"conversion-reporter","fromProcessor":"conversion-converter-1"}
{"level":"warn","ts":1681542808.6231709,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/readloop.go:400","msg":"Failed to create pbq during startup, retrying","vertex":"conversion-reporter","attempt":1,"partitionID":"1681541520000-1681541580000-slot-0","error":"failed to create a PBQ store, stat /var/numaflow/pbq/wals/segment_1681541520.1681541580.slot-0: permission denied"}
{"level":"info","ts":1681542823.5008092,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/processor_manager.go:184","msg":"v.AddProcessor successfully added a new fromProcessor","vertex":"conversion-reporter","fromProcessor":"conversion-converter-3"
