### ISSUE TITLE
Implement per-partition rate calculation and display it on UI

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#746]
As we migrate to metric-based rate calculation, we no longer have partition level processing rates for reduce vertex. The processing rates we delivered through daemon are ALL per vertex. Therefore we no longer support the per-partition rate feature:

![Screenshot 2023-05-24 at 5 59 23 PM](https://github.com/numaproj/numaflow/assets/13165977/e66840e8-004a-4514-9606-c71558fed3a9)

In this task, we implement per-partition rate calculation and display it on UI.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
per-partition metric is very useful to detect hot-key problems.

**Comment by KeranYang** [comment]
> per-partition metric is very useful to detect hot-key problems.

Updated the task description to `Implement per-partition rate calculation and display it on UI`
