### ISSUE TITLE
Enhance the watermark to support multi-partitioned edges.

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#748]

**Comment by KeranYang** [comment]
@yhl25 , I pulled your latest multi-partition changes and started seeing -1 watermark as follow. I am wondering if it's as expected and will be fixed once we close this issue?
![Screenshot 2023-05-31 at 2 16 18 PM](https://github.com/numaproj/numaflow/assets/13165977/c40abe0a-0078-49e5-9025-6d5e9c338b5f)

**Comment by jy4096** [comment]
> feat: enhance watermark to support multi-partitioned edges #751

is it the main branch?

**Comment by jy4096** [comment]
> @yhl25 , I pulled your latest multi-partition changes and started seeing -1 watermark as follow. I am wondering if it's as expected and will be fixed once we close this issue? ![Screenshot 2023-05-31 at 2 16 18 PM](https://user-images.githubusercontent.com/13165977/242370886-c40abe0a-0078-49e5-9025-6d5e9c338b5f.png)

Is it the main branch?
