### ISSUE TITLE
Backport fixes from master to 0.8

### ISSUE THREAD

**Issue by louisnow** [numaproj/numaflow#753]
# Summary

Raising an issue to help track a 0.8.1 release 

https://github.com/numaproj/numaflow/issues/749#issuecomment-1562834423

cc @vigith / @whynowy  

# Use Cases

- Currently if a kafka message is too big, we have no way of proceeding ahead in the source vertex

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
@whynowy, the only blocker for this is #739, right?

**Comment by whynowy** [comment]
> @whynowy, the only blocker for this is #739, right?



> @whynowy, the only blocker for this is #739, right?

Correct.

**Comment by vigith** [comment]
let's track it for this week.

**Comment by vigith** [comment]
released [v0.8.1](https://github.com/numaproj/numaflow/releases/tag/v0.8.1)
