### ISSUE TITLE
Fix potential incorrect processing rate calculation

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#846]
**Describe the bug**
Described in https://github.com/numaproj/numaflow/pull/810#discussion_r1261203309

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
<img width="1536" alt="Screenshot 2023-07-12 at 2 00 12 PM" src="https://github.com/numaproj/numaflow/assets/2832028/f04ce914-2bb5-4b48-892a-2b2b22dd597f">

**Comment by whynowy** [comment]
<img width="1108" alt="Screenshot 2023-07-12 at 2 02 20 PM" src="https://github.com/numaproj/numaflow/assets/2832028/9b2695a8-8e3c-4eeb-b61b-a60deb45a3a9">
