### ISSUE TITLE
Spikes seen in Source Transformer when auto scaling

### ISSUE THREAD

**Issue by RohanAshar** [numaproj/numaflow#859]
**Describe the bug**
During stead traffic we see there are spikes in the source transformer read messages when auto scaling is enabled. The following behavior was observed with min and max set to 1 and 5 respectively. The issue resolved itself when both the min and max were set to 5.

**Expected behavior**
The read messages should follow the same behavior irrespective of auto scaling.

**Screenshots**
<img width="1720" alt="image" src="https://github.com/numaproj/numaflow/assets/11658125/15051d7a-d336-453a-9474-6052ed6beefe">

**Environment (please complete the following information):**
- Numaflow: v0.9.0-rc1
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
Please try out 0.9.0-rc2, which includes #846, which should alleviate this issue.

**Comment by RohanAshar** [comment]
Upgrading to 0.9.0-rc2 did not work. It still has the same behavior.

**Comment by kohlisid** [comment]
Closing as issue not seen, will reopen if observed again.
