### ISSUE TITLE
Be able to pass metadata across vertices with message body

### ISSUE THREAD

**Issue by inshbha2** [numaproj/numaflow#877]
# Summary

Be able to pass metadata from one vertex to another without it being part of the message body.

# Use Cases

We have a string field that is required to identify a specific config, this field does not really belong to the message body being passed along to the next vertex , would be good to have it just like an extra info that is being passed.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
Why doesn't it belong to the message body? Isn't that metadata part of user logic?

**Comment by inshbha2** [comment]
yup it is a raw metric name which we read from the source and use to identify the config in the first vertex and then transform the message to only include the fields that will be part of the final output .

**Comment by vigith** [comment]
the logic of how to use that field is very custom to the user's code/logic. Numaflow as a platform cannot generalize it, e.g., how will numaflow handle this from a reduce standpoint, since it is an m:n (where m > n) kind of operation?

**Comment by vigith** [comment]
as discussed, this is not platform-specific, but rather user-logic-specific.
