### ISSUE TITLE
Be able to add label to every vertex in a pipeline by specifying it in a single place

### ISSUE THREAD

**Issue by inshbha2** [numaproj/numaflow#878]
# Summary

It would be good to be able to add a label in a single place for it to be picked up as a label in all the vertices within the pipeline.

# Use Cases

We have a label for splunk index, also another label which we use as a selector for prometheus metrics that is required in all vertices, currently we add it as a label individually to every vertex, but it would be good to be able to add the label in a single place like the pipeline labels (with an optional tag or something similar) that would make the label a part of every vertex.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
We could introduce `spec.templates.vertex` in Pipeline spec, which defines the template for the pods of all the vertices. The template may include:

- `AbstractPodTemplate`, which have `metadata` included for labels and annotations;
- `ContainerTemplate`, which is for the numa container of each vertex pod;
- `InitContainerTemplate`, which is for the init container of each vertex pod.

These templates can be overwritten by the specification of each vertex.

**Comment by whynowy** [comment]
@inshbha2 - for prometheus metrics, if it's only for the label selector in a Service definition to select all the vertex pods, you can use:

```
    app.kubernetes.io/component: vertex
    app.kubernetes.io/managed-by: vertex-controller
    app.kubernetes.io/part-of: numaflow
    numaflow.numaproj.io/pipeline-name: <pipeline-name>
```

**Comment by inshbha2** [comment]
we tried using numaflow.numaproj.io/pipeline-name: <pipeline-name> , but we have two different pipelines for which we want to capture the same metrics , so couldnt use that. 
Yes, we can use 'app.kubernetes.io/component: vertex'
