### ISSUE TITLE
NoOp watermark support

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#88]
use NoOp watermark progressor and avoid nil checks in forwarder.

**Comment by vigith** [comment]
this is not done, we have `nil` check in forwarder.

**Comment by vigith** [comment]
we need to fix sources, they are still passing `nil`

**Comment by kohlisid** [comment]
@vigith - I'll pick this up and check the what's the issue

**Comment by whynowy** [comment]
> 

@kohlisid - I think we are good, we don't need to get rid of those `nil`s particularly, as we implementing WM for all the sources, they will be gone.
