### ISSUE TITLE
SDK signatures are confusing as it passes compile time but will not work es expected at the runtime

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#906]
```go
func reduceHandle(_ context.Context, _ []string, _ <-chan functionsdk.Datum, _ functionsdk.Metadata) functionsdk.Messages  {
  return 
}

func handle(_ context.Context, _ []string, _ functionsdk.Datum) functionsdk.Messages {
  return 
}

func main() {
	server.New().RegisterReducer(functionsdk.ReduceFunc(reduceHandle)).RegisterMapper(functionsdk.MapFunc(handle)).Start(context.Background())
}
```

the above syntax will pass compile time but will not work. Please **note** that I have registered both `map` and `reduce` to the same server which is semantically wrong.

The bug part of the SDK is the fact that we allow registering of any number of map/reduce handlers even though we keep the last one for each type.

**Comment by jy4096** [comment]
why won’t it work?… it can be considered as an image which can be used as either reduce or map
and whether we use it as map or a reduce depends on the pipeline.yaml file??.....

**Comment by vigith** [comment]
But a vertex cannot be both. It can only be a map or a reduce vertex. If a user passes it and it is accepted, they would imagine that that vertex is doing two things.

Our implementation can be **confusing** to users, it is not a bug.

**Comment by ashwinidulams** [comment]
in this case, is there any error that you see? curious as to whats the behaviour currently

**Comment by vigith** [comment]
this is not an error, just a confusing behavior. we (numa) will invoke the right handler.

**Comment by vigith** [comment]
The bug part of the SDK is the fact that we allow registering of any number of map/reduce handlers even though we keep the last one for each type.

**Comment by yhl25** [comment]
closed by - https://github.com/numaproj/numaflow-go/pull/70
