### ISSUE TITLE
Kafka source to ingest from a specific offset

### ISSUE THREAD

**Issue by alexanghh** [numaproj/numaflow#925]
# Summary

Allow configuration of Kafka source to ingest from a specific offset

What change needs making?

Kafka source.

# Use Cases

- When creating a new pipeline which requires to ingest from specific point in time/offset.
- When fixing bugs/new features in pipeline and re-ingesting partially from kafka topic.

PS: I can help to implement this but would like to seek advice if this is as simple as adding the offset configuration in the kafka source (e.g. would the kafka source pods get restart, and use the offset in the configuration?)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by yhl25** [comment]
Thank you for creating this issue. While Sarama does not directly support reading from a specific time, it does provide the functionality to read from a specific offset. This can be achieved using the [ResetOffset()](https://github.com/IBM/sarama/blob/23c42869222b1467841a9b6318a7ceb159c6a6fd/consumer_group.go#L644) method. I am currently investigating this feature to understand it better and will update you with any findings or potential solutions.

**Comment by yhl25** [comment]
Following my testing, I have been able to utilize the ResetOffset() method from Sarama to facilitate consumption from a specific offset I think we can offer this feature in our Kafka source. Since the offset is unique to each partition, how do we allow users to specify the offsets in the pipeline spec? any suggestions? @vigith @whynowy @alexanghh

**Comment by alexanghh** [comment]
Hi @yhl25, may I proceed to implement the Consumer.Offsets.Initial first while figuring out the viability of setting specific offset?
At least making it possible to consume from the oldest offset. Current implementation only allows msg to be consumed from the newest.

**Comment by alexanghh** [comment]
> Following my testing, I have been able to utilize the ResetOffset() method from Sarama to facilitate consumption from a specific offset I think we can offer this feature in our Kafka source. Since the offset is unique to each partition, how do we allow users to specify the offsets in the pipeline spec? any suggestions? @vigith @whynowy @alexanghh

May I suggest to use a map to store the offsets per partition? This would be similar to what [Apache Spark](https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html) (referencing startingOffsetsByTimestamp and startingOffsets) has done.

Also, it is possible to retrieve the offsets by timestamp using [GetOffset()](https://github.com/IBM/sarama/blob/23c42869222b1467841a9b6318a7ceb159c6a6fd/client.go#L77C4-L77C4). 

On setting of the offsets, I would like to check where would be the best place to implement it? Since the offsets should only be set once on pipeline deployment and not subsequently when pod restarts.

**Comment by vigith** [comment]
@alexanghh, yes, pod restarts are a problem. offsets themselves are managed by kafka but if we hard code the value then during restart it will start again from the value we have put in the config. perhaps we should mutate the value outside of numaflow?

Today in Numaflow, we do not have a source coordinator, we will be incorporating that when we are implementing the bounded stream.

**Comment by alexanghh** [comment]
Hi @vigith, when you mention mutating the value outside of numaflow, do you mean 
1. it shouldn't be handled by numaflow at all and it should be handled externally (e.g. changing the offsets via kafka cli prior to applying pipeline) or 
2. handle it outside of the flow/pipeline such as during pipeline initialization (similar to the concept of init container but for the pipeline instead of vertex - maybe handled in pipeline controller/reconciler)?

**Comment by whynowy** [comment]
> Managed to set the Consumer.Offsets.Initial using the kafka config as follows (for interim):
> 
> ```
>       source:
>         kafka:
>           brokers:
>             - "broker_ip:port"
>           topic: "topic"
>           consumerGroup: "group"
>           config: |
>             Consumer:
>               Offsets:
>                 Initial: -2 # -2 for sarama.OffsetOldest, -1 for sarama.OffsetNewest
> ```
> 
> Updating here in case anyone else needs it, since it is not available in the docs.

This should be added to our doc as well.
