### ISSUE TITLE
UI - vertex (number of pods) flows out of the box

### ISSUE THREAD

**Issue by inshbha2** [numaproj/numaflow#938]
**Describe the bug**
When the vertex name is long, in the UI , name (number of pods) flows out of the box as shown in screenshot.

**To Reproduce**

1. Create a vertex with long name
2. Deploy pipeline and load the UI

**Expected behavior**
Name should be either truncated and have a tool tip to show the entire name or box size should be adjusted to fit the name

**Screenshots**
<img width="1417" alt="Screenshot 2023-08-08 at 12 14 41 PM" src="https://github.com/numaproj/numaflow/assets/12195283/8dbc4214-40c8-482a-a0a0-a9a8bb854430">

**Environment (please complete the following information):**
- Numaflow: [e.g. v0.9]

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
perhaps we should remove the word pods, i am assuming it is obvious :) 

@malinamfong we need a designer for this.

**Comment by vigith** [comment]
@mshakira @darshansimha @veds-g did we fix this in the new UI? if yes, please close.

**Comment by veds-g** [comment]
we did fix it with the new UI.
