### ISSUE TITLE
numaflowUI: Connection line is missing between vertices 

### ISSUE THREAD

**Issue by sarabala1979** [numaproj/numaflow#952]
**Describe the bug**
Connection line is missing between vertices. UI version: v0.9.1
<img width="349" alt="image" src="https://github.com/numaproj/numaflow/assets/33908564/137c134e-2749-4b61-ac7d-f2c8d7adc017">

**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
@vigith Is this issue fixed on the latest UI? We are using Numaflow controller v0.9.2 and Numaflow UI: v0.9.1. Still able reproduce it.

**Comment by vigith** [comment]
Can please update the issue with new screenshots?

**Comment by sarabala1979** [comment]
<img width="1072" alt="image" src="https://github.com/numaproj/numaflow/assets/33908564/24cc2e24-754d-4406-ba35-828966d8064b">
