### ISSUE TITLE
Processing rate displayed on UI is off

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#984]
**Describe the bug**

<img width="348" alt="Screenshot 2023-08-23 at 6 42 08 PM" src="https://github.com/numaproj/numaflow/assets/13165977/db0b8307-1303-46e1-880d-d96be33db54d">

**To Reproduce**
Work with Shashank to create the FCI load-testing pipeline and we should be able to see the bug. https://github.intuit.com/oss-analytics/numalogic-osam-fci-deployment/blob/master/environments/stg-usw2-eks/numalogic-osam-fci.yaml

**Comment by vigith** [comment]
@KeranYang is this still an issue?

**Comment by KeranYang** [comment]
@vigith It could be. I didn't get a chance to follow up on it. This could be a bug that only happens when TPS is as high as the load test.

**Comment by KeranYang** [comment]
I don't think we have seen this issue anymore in the past 6+ months. We had multiple bug fixes for the processing rate, one of which might have fixed this issue. I am closing it.
