### ISSUE TITLE
Pause a pipeline does not terminate reduce vertex pods

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#990]
**Describe the bug**

When pause a pipeline with `kubectl patch pl my-pipeline --type=merge --patch '{"spec": {"lifecycle": {"desiredPhase": "Paused"}}}'`, it only the map vertex pods get terminated, while reduce vertex pods are still running.

**Comment by vigith** [comment]
it needs the WAL stored in the disk; reduce is stateful, and cannot rely just on ISB.

**Comment by whynowy** [comment]
> it needs the WAL stored in the disk; reduce is stateful, and cannot rely just on ISB.

If needs the PVC attached as the WAL, we can call out that in the doc. But when pausing, we should terminate the pods.
